"""add train_lines

Revision ID: 5c32e4234f2b
Revises: dad15e276ca2
Create Date: 2025-11-23 22:22:33.597448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c32e4234f2b'
down_revision = 'dad15e276ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_city_id', sa.Integer(), nullable=False),
    sa.Column('to_city_id', sa.Integer(), nullable=False),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('distance_units', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['to_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train_lines')
    # ### end Alembic commands ###
