"""add agent meta columns

Revision ID: 687c45aabe1d
Revises: 0b1f6a3cfe1e
Create Date: 2025-12-05 15:48:23.344489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687c45aabe1d'
down_revision = '0b1f6a3cfe1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codename', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=False, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('infection_level', sa.Integer(), nullable=False, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('last_action_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_agents_codename', ['codename'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_agents_codename', type_='unique')
        batch_op.drop_column('last_action_at')
        batch_op.drop_column('infection_level')
        batch_op.drop_column('credits')
        batch_op.drop_column('codename')

    # ### end Alembic commands ###
