# cities_seed.py

from models import db
from models.region import Region
from models.city import City

REGIONS = {
    "pacific_northwest": "Pacific Northwest",
    "pacific_southwest": "Pacific Southwest",
    "mountain": "Mountain",
    "midwest_north": "Midwest North",
    "midwest_central": "Midwest Central",
    "southwest": "Southwest",
    "south_central": "South Central",
    "southeast": "Southeast",
    "northeast": "Northeast",
}

STATE_MAP = {
    "Seattle": ("Washington", "WA"),
    "Portland": ("Oregon", "OR"),
    "Spokane": ("Washington", "WA"),
    "Olympia": ("Washington", "WA"),
    "Salem": ("Oregon", "OR"),
    "Astoria": ("Oregon", "OR"),
    "Boise": ("Idaho", "ID"),
    "Helena": ("Montana", "MT"),
    "Bismarck": ("North Dakota", "ND"),
    "San Francisco": ("California", "CA"),
    "Oakland": ("California", "CA"),
    "San Jose": ("California", "CA"),
    "Sacramento": ("California", "CA"),
    "Fresno": ("California", "CA"),
    "Bakersfield": ("California", "CA"),
    "Los Angeles": ("California", "CA"),
    "San Diego": ("California", "CA"),
    "Eureka": ("California", "CA"),
    "Las Vegas": ("Nevada", "NV"),
    "Phoenix": ("Arizona", "AZ"),
    "Tucson": ("Arizona", "AZ"),
    "Salt Lake City": ("Utah", "UT"),
    "Denver": ("Colorado", "CO"),
    "Colorado Springs": ("Colorado", "CO"),
    "Santa Fe": ("New Mexico", "NM"),
    "Albuquerque": ("New Mexico", "NM"),
    "Cheyenne": ("Wyoming", "WY"),
    "Pierre": ("South Dakota", "SD"),
    "Sheridan": ("Wyoming", "WY"),
    "Minneapolis": ("Minnesota", "MN"),
    "Milwaukee": ("Wisconsin", "WI"),
    "Chicago": ("Illinois", "IL"),
    "Detroit": ("Michigan", "MI"),
    "Kansas City": ("Missouri", "MO"),
    "St. Louis": ("Missouri", "MO"),
    "Indianapolis": ("Indiana", "IN"),
    "Cincinnati": ("Ohio", "OH"),
    "Columbus": ("Ohio", "OH"),
    "Omaha": ("Nebraska", "NE"),
    "Wichita": ("Kansas", "KS"),
    "Tulsa": ("Oklahoma", "OK"),
    "Oklahoma City": ("Oklahoma", "OK"),
    "Little Rock": ("Arkansas", "AR"),
    "El Paso": ("Texas", "TX"),
    "Amarillo": ("Texas", "TX"),
    "Dallas": ("Texas", "TX"),
    "Austin": ("Texas", "TX"),
    "San Antonio": ("Texas", "TX"),
    "Houston": ("Texas", "TX"),
    "Wichita Falls": ("Texas", "TX"),
    "Galveston": ("Texas", "TX"),
    "Odessa": ("Texas", "TX"),
    "San Angelo": ("Texas", "TX"),
    "Grand Marais": ("Minnesota", "MN"),
    "Escanaba": ("Michigan", "MI"),
    "Casper": ("Wyoming", "WY"),
    "Monticello": ("Utah", "UT"),
    "Ely": ("Nevada", "NV"),
    "Williston": ("North Dakota", "ND"),
    "Jackson": ("Mississippi", "MS"),
    "New Orleans": ("Louisiana", "LA"),
    "Memphis": ("Tennessee", "TN"),
    "Atlanta": ("Georgia", "GA"),
    "Augusta": ("Maine", "ME"),
    "Montgomery": ("Alabama", "AL"),
    "Charlotte": ("North Carolina", "NC"),
    "Raleigh": ("North Carolina", "NC"),
    "Jacksonville": ("Florida", "FL"),
    "Tampa": ("Florida", "FL"),
    "Miami": ("Florida", "FL"),
    "Pittsburgh": ("Pennsylvania", "PA"),
    "Cleveland": ("Ohio", "OH"),
    "Buffalo": ("New York", "NY"),
    "Albany": ("New York", "NY"),
    "New York": ("New York", "NY"),
    "Philadelphia": ("Pennsylvania", "PA"),
    "Baltimore": ("Maryland", "MD"),
    "Washington": ("District of Columbia", "DC"),
    "Boston": ("Massachusetts", "MA"),
    "Concord": ("New Hampshire", "NH"),
    "Richmond": ("Virginia", "VA"),
    "Columbia": ("South Carolina", "SC"),
    "Birmingham": ("Alabama", "AL"),
    "Baton Rouge": ("Louisiana", "LA"),
    "Tallahassee": ("Florida", "FL"),
    "Orlando": ("Florida", "FL"),
    "Nashville": ("Tennessee", "TN"),
    "Springfield": ("Illinois", "IL"),
    "Jefferson City": ("Missouri", "MO"),
    "Topeka": ("Kansas", "KS"),
    "Lincoln": ("Nebraska", "NE"),
    "Louisville": ("Kentucky", "KY"),
}

DESCRIPTION_MAP = {
    "Seattle": "Přístavní metropole Pacifiku.\nMěsto technologických gigantů a kaváren.\nDeštivá kulisa s výhledem na Mt. Rainier.",
    "Portland": "Město mostů a řeky Willamette.\nZnámé craft pivem a food-trucky.\nZelené parky, cyklo kultura a klidný vibe.",
    "Spokane": "Východní Washington na řece Spokane.\nHistorické centrum se starými mlýny.\nBrána k horám a outdooru Inland Empire.",
    "Olympia": "Hlavní město státu Washington u Puget Sound.\nKompaktní downtown, Capitol a přístavní promenáda.\nBrána mezi Seattle a národní park Olympic.",
    "Salem": "Kapitál Oregonu na řece Willamette.\nHistorické ulice, vinice v okolí a státní úřady.\nKlidnější alternativa k Portlandu.",
    "Astoria": "Pobřežní město u ústí řeky Columbia.\nHistorie rybářů a námořnictva, most Astoria-Megler.\nMlžné kopce a výhledy na Pacifik.",
    "Boise": "Horská metropole Idaha v údolí Treasure Valley.\nSilná scéna trailů a řeky Boise.\nMix technologií a univerzitního života.",
    "Helena": "Kapitál Montany v podhůří.\nMalé historické centrum a zlatokopecká stopa.\nVýchozí bod k jezerům a divočině.",
    "Bismarck": "Kapitál Severní Dakoty na řece Missouri.\nRostoucí energetický uzel Velkých plání.\nKlidné město s širokými bulváry.",
    "San Francisco": "Město zálivu a ikonického Golden Gate.\nStrmé ulice, lanovky a otevřený tech svět.\nMix viktoriánské architektury a startupů.",
    "Oakland": "Hlavní přístav East Bay.\nŽivá hudební a street art scéna.\nIndustrial vibe s výhledy na SF skyline.",
    "San Jose": "Srdce Silicon Valley.\nDomov velkých technologických kampusů.\nSlunné předměstí s vysokým tempem inovací.",
    "Sacramento": "Kapitál Kalifornie na soutoku řek.\nHistorie zlaté horečky a státní správa.\nRostoucí food & farm-to-fork scéna.",
    "Fresno": "Brána do údolí San Joaquin.\nZemědělské centrum s parkem Yosemite poblíž.\nHorká léta a přímočará dopravní síť.",
    "Bakersfield": "Energetické a agro centrum Kalifornie.\nCountry hudba v duchu Bakersfield soundu.\nNa půli cesty mezi LA a Sierra Nevada.",
    "Los Angeles": "Rozlehlá metropole filmového průmyslu.\nPláže, Hollywood a nekonečné dálnice.\nMix kultur, čtvrtí a kreativních odvětví.",
    "San Diego": "Slunné přímořské město u mexické hranice.\nNámořní základny, surfaři a zoo světové úrovně.\nStálé podnebí s palmami a promenádami.",
    "Eureka": "Pobřežní město mezi sekvoji.\nVictoriánské domy a přístavní historie.\nChladné mlhy a blízkost Redwood National Park.",
    "Las Vegas": "Pouštní město neonů a kasin.\nStrip s hotely a show nonstop.\nBrána k Red Rock a Valley of Fire.",
    "Phoenix": "Rozlehlá metropole Arizony v Sonorské poušti.\nHorká léta, golfová hřiště a tech parky.\nRychle rostoucí populace a dálnice do všech směrů.",
    "Tucson": "Pouštní město pod horami Santa Catalina.\nUniverzitní atmosféra a bohatá hispánská kultura.\nTemné nebe pro astronomy a saguaro kaktusy všude.",
    "Salt Lake City": "Metropole Utahu s výhledem na Wasatch.\nCentrum zimních sportů a jezera Great Salt Lake.\nČisté ulice, moderní downtown a hory na dosah.",
    "Denver": "Mílové město na úpatí Rockies.\nPivo, sport a rychle rostoucí tech scéna.\nČistý vzduch a výjezdy do hor za chvíli.",
    "Colorado Springs": "Pod Pikes Peak na Front Range.\nVojenské akademie a zahrady Garden of the Gods.\nKlidnější alternativa k Denveru.",
    "Santa Fe": "Pueblo architektura a galerie jihozápadu.\nNejstarší hlavní město USA s adobe centrem.\nChilies, umění a vysoká nadmořská výška.",
    "Albuquerque": "Balónové město na řece Rio Grande.\nRoute 66, Breaking Bad a mix kultur.\nSuché klima a pohled na Sandia Mountains.",
    "Cheyenne": "Kovbojské hlavní město Wyomingu.\nFrontier Days rodeo a železniční dědictví.\nVítr, prérie a otevřené nebe.",
    "Pierre": "Malý kapitál Jižní Dakoty na Missouri.\nKlidné správní centrum plání.\nRybaření a široké horizonty všude kolem.",
    "Sheridan": "Pod Bighorn Mountains ve Wyomingu.\nHistorie skotu a westernu.\nBrána k trailům a rančerské kultuře.",
    "Minneapolis": "Město jezer a cyklostezek.\nKultura divadel a hudby na Mississippi.\nSoučást dvojčat s Saint Paul.",
    "Milwaukee": "Pivní město na břehu Michiganského jezera.\nCyklo promenády, Harley-Davidson muzeum.\nČeské a německé kořeny ve čtvrtích.",
    "Chicago": "Vítr u Michiganského jezera a mrakodrapy.\nDeep-dish pizza, blues a velký průmysl.\nIkonická silueta a Lake Shore Drive.",
    "Detroit": "Motor City s dědictvím automobilky.\nMotown hudba a ožívající centrum.\nNa řece Detroit s výhledem na Kanadu.",
    "Kansas City": "Město barbecue a jazzových klubů.\nFontány a dělené státní hranicí Missouri/Kansas.\nSilný sportovní fandom a boulevardy.",
    "St. Louis": "Gateway Arch na Mississippi.\nHistorie průkopníků a baseballu.\nMix blues, barbecue a řeky.",
    "Indianapolis": "Domov Indy 500 a motorsportu.\nKompaktní downtown s kanálem.\nRostoucí tech a zdravotnický hub Středozápadu.",
    "Cincinnati": "Město na Ohio s historickými pivovary.\nKopcovité čtvrti a most Roebling.\nSměs středozápadní a jižanské kultury.",
    "Columbus": "Univerzitní město Ohio State.\nRostoucí tech scéna a čistý downtown.\nCentrální poloha v Ohiu.",
    "Omaha": "Missourské město s logistickým uzlem.\nHistorie stockyards a moderní centrum.\nSilné firemní zázemí a zoo světové třídy.",
    "Wichita": "Letecké město Kansasu.\nPrůmysl letadel a prérijní horizonty.\nKlidná metropole s muzei letectví.",
    "Tulsa": "Art Deco perla Oklahomy.\nRopa, blues a Route 66.\nNové parky podél Arkansas River.",
    "Oklahoma City": "Hlavní město Oklahomy u řeky North Canadian.\nCapitol s ropnou věží, cowboy kultura a NBA Thunder.\nRostoucí downtown s Bricktown kanálem.",
    "Little Rock": "Kapitál Arkansasu na řece Arkansas.\nPřístup k Ozark a historii občanských práv.\nKompaktní downtown s mosty.",
    "El Paso": "Hranice s Mexikem na Rio Grande.\nDvojměstí s Ciudad Juárez a pohoří Franklin.\nSuché klima, pevnosti a tex-mex kuchyně.",
    "Amarillo": "Prérijní Texas na I-40.\nCadillac Ranch a panhandle tradice.\nVítr, dálavy a steaky.",
    "Dallas": "Moderní metropole severního Texasu.\nMrakodrapy, finance a sportovní kluby.\nMuzea, parky a široké dálnice.",
    "Austin": "Hlavní město Texasu a live music.\nTech hub s festivaly SXSW.\nZelené pásy kolem Lady Bird Lake.",
    "San Antonio": "Historie Alama a řeka River Walk.\nMise UNESCO a bohatá hispánská kultura.\nVelké vojenské zázemí.",
    "Houston": "Energetická metropole a NASA.\nRozlehlé dálnice, port a bayou.\nRozmanitá kuchyně a velké muzea.",
    "Wichita Falls": "Severní Texas na Wichita River.\nLetecká základna Sheppard AFB a malá downtown scéna.\nBrána mezi Dallasem a Oklahomou.",
    "Galveston": "Pobřežní město na ostrově v Mexickém zálivu.\nHistorické centrum, přístav a pláže.\nVýchozí bod pro výletní lodě a rybáře.",
    "Odessa": "Západní Texas na Permian Basin.\nRopa, pumpjacky a měsíční krajina kolem.\nHlavní uzel mezi Midlandem a Pecosem.",
    "San Angelo": "Střední Texas na řece Concho.\nHistorické Fort Concho, jezera a západní vibe.\nKřižovatka rancherské oblasti a univerzity.",
    "Grand Marais": "Severní břeh Lake Superior v Minnesotě.\nMalý přístav, Boreal forest a výchozí bod k Boundary Waters.\nKreativní komunita a polární záře v zimě.",
    "Escanaba": "Hrabství Delta na pobřeží Michiganského jezera.\nPřístav, papírny a rybářská tradice.\nTiché město horního poloostrova (UP).",
    "Casper": "Hlavní město Wyomingův ropného boomu u North Platte River.\nŽelezniční a energetický uzel na High Plains.\nBrána do Casper Mountain a prérie.",
    "Monticello": "Malé město jihovýchodního Utahu u La Sal Mountains.\nBrána k Canyonlands a Bears Ears.\nKlidná základna pro roadtripy po red rock krajině.",
    "Ely": "Osvědčená zastávka v Nevadě u US-50.\nHistorie těžby, železnice a Great Basin National Park poblíž.\nStargazing a tiché vysoké pouště.",
    "Williston": "Ropné město severní Dakoty v oblasti Bakken.\nBoomtown s přístavem na řece Missouri.\nZázemí pro těžbu, logistiku a dálkové trasy na sever.",
    "Jackson": "Kapitál Mississippi na I-55.\nSoulová hudba a občanská práva.\nJižanské jídlo a pomalejší tempo.",
    "New Orleans": "Město jazzu a Mardi Gras.\nFrench Quarter, Cajun kuchyně a delta Mississippi.\nVlkhkost, říční přístav a noční život.",
    "Memphis": "Domov blues na Beale Street.\nGraceland a Mississippi Riverfront.\nBarbecue a hudební dědictví.",
    "Atlanta": "Hlavní uzel jihovýchodu.\nDopravní hub, filmový průmysl a korporace.\nZelené čtvrti a centrum občanských práv.",
    "Augusta": "Hlavní město Maine na Kennebec River.\nKlidné správní centrum Nové Anglie.\nBrána k lesům a pobřeží severovýchodu.",
    "Montgomery": "Kapitál Alabamy na řece Alabama.\nKlíčové místo hnutí za občanská práva.\nJižanská architektura a teplé klima.",
    "Charlotte": "Bankovní centrum Caroliny.\nRostoucí skyline a NASCAR Hall of Fame.\nParky, zelené čtvrti a finance.",
    "Raleigh": "Součást Research Triangle.\nUniverzity, tech parky a dubové stromy.\nVyvážené město vědy a kultury.",
    "Jacksonville": "Největší město Floridy podle rozlohy.\nPobřežní pláže a řeka St. Johns.\nSilné vojenské námořní zázemí.",
    "Tampa": "Záliv Tampa Bay a Gasparilla.\nPřístav, pláže a sportovní arény.\nKubánský vliv z Ybor City.",
    "Miami": "Tropická metropole jihu Floridy.\nArt Deco, pláže a latinská kultura.\nBrána do Karibiku a Latinské Ameriky.",
    "Pittsburgh": "Město mostů na soutoku tří řek.\nOcelová historie a univerzity.\nKopce, žluté mosty a sportovní vášeň.",
    "Cleveland": "Na břehu Erijského jezera.\nRock & Roll Hall of Fame a průmyslové kořeny.\nObnova nábřeží a sportovní týmy.",
    "Buffalo": "Severní New York u Niagarských vodopádů.\nHistorie výroby a zimní sníh.\nHorká křidélka a jezero Erie.",
    "Albany": "Kapitál státu New York u řeky Hudson.\nHistorická architektura a státní úřady.\nBrána do Adirondacks.",
    "New York": "Neuspávající město pěti čtvrtí.\nWall Street, Broadway a Central Park.\nIkony mrakodrapů a diverzita světa.",
    "Philadelphia": "Město bratrské lásky.\nHistorie nezávislosti a cheesesteaků.\nKultura muzeí a sportu.",
    "Baltimore": "Přístavní město Inner Harbor.\nEdgar Allan Poe a modří raci.\nCihlové řadovky a výhled na Chesapeake Bay.",
    "Washington": "Hlavní město USA na Potomacu.\nKapitol, Bílý dům a muzea Smithsonian.\nMonumenty a federální čtvrti.",
    "Boston": "Historické jádro Nové Anglie.\nUniverzity, přístav a Freedom Trail.\nCihlové uličky, sport a Atlantik.",
    "Concord": "Hlavní město New Hampshire u Merrimack River.\nKompaktní centrum se státním Capitolem.\nZázemí pro výlety do White Mountains.",
    "Richmond": "Historické hlavní město Virginie na James River.\nCihlové čtvrti, street art a craft scéna.\nDůležitý dopravní uzel mezi DC a Jihovýchodem.",
    "Columbia": "Hlavní město Jižní Karolíny na Congaree River.\nUniverzitní město a státní instituce.\nHorká léta, parky a vojenská tradice Fort Jackson.",
    "Birmingham": "Průmyslové srdce Alabamy v podhůří Appalachian.\nHistorie železnic, občanských práv a bourbonek.\nRostoucí tech a zdravotnická scéna.",
    "Baton Rouge": "Hlavní město Louisiany na řece Mississippi.\nKapitól, LSU a směs cajun/kreolské kultury.\nPetrochemie, přístav a povodňové hráze.",
    "Tallahassee": "Kapitál Floridy na kopcích Panhandlu.\nStátní instituce, FSU kampus a dubové aleje.\nBlízko pobřeží Gulf Coast a Apalachicola Forest.",
    "Orlando": "Centrální Florida s resorty a kongresy.\nTheme parky, jezera a rychle rostoucí downtown.\nDopravní uzel mezi Miami a Jacksonville.",
    "Nashville": "Hudební metropole Tennesse – country, honky-tonk bary a Grand Ole Opry.\nRostoucí tech a zdravotnický sektor.\nHlava státu uprostřed kopcovité střední Tennessee.",
    "Springfield": "Hlavní město Illinois s Capitolem a Lincolnovou historií.\nKompaktní centrum uprostřed prérijního státu.\nSpráva, muzea a Route 66 nálada.",
    "Jefferson City": "Kapitál Missouri na řece Missouri.\nKopcovité centrum s Capitolem a státní správou.\nKlidnější město mezi Kansas City a St. Louis.",
    "Topeka": "Hlavní město Kansasu na řece Kansas.\nHistorie občanských práv a státní instituce.\nPrérijní horizonty a klidné čtvrti.",
    "Lincoln": "Hlavní město Nebrasky s univerzitním kampusem.\nCapitol s věží a prérijní panorama.\nZázemí agrárního státu s rostoucím tech sektorem.",
    "Louisville": "Kentucké město na řece Ohio a Derby tradic.\nMosty mezi Kentucky a Indianou, mix bourbonu a baseballu.\nRozlehlý parkový systém a rostoucí logistické huby.",
}

CITIES = [
    {
        "name": "Seattle",
        "region": "pacific_northwest",
        "importance": 1,
        "lat": 46.9062,
        "lon": -119.1321,
        "px": 72.38,
        "py": 69.5,
        "grid_x": 8,
        "grid_y": 9,
    },
    {
        "name": "Olympia",
        "region": "pacific_northwest",
        "importance": 2,
        "lat": 47.0379,
        "lon": -122.9007,
        "px": 68.0,
        "py": 82.0,
        "grid_x": 8,
        "grid_y": 11,
    },
    {
        "name": "Portland",
        "region": "pacific_northwest",
        "importance": 3,
        "lat": 45.2051,
        "lon": -119.725,
        "px": 61.61,
        "py": 109.61,
        "grid_x": 7,
        "grid_y": 14,
    },
    {
        "name": "Astoria",
        "region": "pacific_northwest",
        "importance": 3,
        "lat": 46.1879,
        "lon": -123.8313,
        "px": 49.0,
        "py": 95.0,
        "grid_x": 5,
        "grid_y": 12,
    },
    {
        "name": "Salem",
        "region": "pacific_northwest",
        "importance": 2,
        "lat": 44.9429,
        "lon": -123.0351,
        "px": 60.0,
        "py": 122.0,
        "grid_x": 8,
        "grid_y": 17,
    },
    {
        "name": "Spokane",
        "region": "pacific_northwest",
        "importance": 3,
        "lat": 46.0588,
        "lon": -115.426,
        "px": 134.73,
        "py": 89.48,
        "grid_x": 17,
        "grid_y": 11,
    },
    {
        "name": "Boise",
        "region": "pacific_northwest",
        "importance": 2,
        "lat": 42.115,
        "lon": -115.1023,
        "px": 140.62,
        "py": 182.46,
        "grid_x": 18,
        "grid_y": 23,
    },
    {
        "name": "Helena",
        "region": "pacific_northwest",
        "importance": 2,
        "lat": 44.9884,
        "lon": -111.0245,
        "px": 214.72,
        "py": 114.72,
        "grid_x": 27,
        "grid_y": 14,
    },
    {
        "name": "Bismarck",
        "region": "pacific_northwest",
        "importance": 2,
        "lat": 44.2083,
        "lon": -100.7837,
        "px": 400.82,
        "py": 133.11,
        "grid_x": 50,
        "grid_y": 17,
    },
    {
        "name": "San Francisco",
        "region": "pacific_southwest",
        "importance": 2,
        "lat": 37.7749,
        "lon": -121.4194,
        "px": 25.82,
        "py": 284.78,
        "grid_x": 3,
        "grid_y": 36,
    },
    {
        "name": "Oakland",
        "region": "pacific_southwest",
        "importance": 3,
        "lat": 37.9044,
        "lon": -121.2711,
        "px": 28.51,
        "py": 281.73,
        "grid_x": 4,
        "grid_y": 35,
    },
    {
        "name": "San Jose",
        "region": "pacific_southwest",
        "importance": 3,
        "lat": 37.3382,
        "lon": -120.8863,
        "px": 35.51,
        "py": 295.08,
        "grid_x": 4,
        "grid_y": 37,
    },
    {
        "name": "Sacramento",
        "region": "pacific_southwest",
        "importance": 2,
        "lat": 38.5816,
        "lon": -120.5944,
        "px": 40.81,
        "py": 265.76,
        "grid_x": 5,
        "grid_y": 33,
    },
    {
        "name": "Fresno",
        "region": "pacific_southwest",
        "importance": 3,
        "lat": 36.7378,
        "lon": -119.7871,
        "px": 55.48,
        "py": 309.23,
        "grid_x": 7,
        "grid_y": 39,
    },
    {
        "name": "Bakersfield",
        "region": "pacific_southwest",
        "importance": 3,
        "lat": 35.3733,
        "lon": -119.0187,
        "px": 70.44,
        "py": 336.4,
        "grid_x": 9,
        "grid_y": 43,
    },
    {
        "name": "Los Angeles",
        "region": "pacific_southwest",
        "importance": 1,
        "lat": 34.0522,
        "lon": -118.2437,
        "px": 78.53,
        "py": 366.55,
        "grid_x": 10,
        "grid_y": 47,
    },
    {
        "name": "San Diego",
        "region": "pacific_southwest",
        "importance": 2,
        "lat": 32.7157,
        "lon": -117.1611,
        "px": 102.2,
        "py": 395.0,
        "grid_x": 13,
        "grid_y": 49,
    },
    {
        "name": "Eureka",
        "region": "pacific_southwest",
        "importance": 3,
        "lat": 41.0021,
        "lon": -122.1637,
        "px": 12.29,
        "py": 208.7,
        "grid_x": 2,
        "grid_y": 26,
    },
    {
        "name": "Las Vegas",
        "region": "mountain",
        "importance": 3,
        "lat": 36.1699,
        "lon": -115.1398,
        "px": 139.93,
        "py": 332.62,
        "grid_x": 17,
        "grid_y": 40,
    },
    {
        "name": "Phoenix",
        "region": "mountain",
        "importance": 2,
        "lat": 32.8484,
        "lon": -112.074,
        "px": 195.65,
        "py": 400.93,
        "grid_x": 24,
        "grid_y": 50,
    },
    {
        "name": "Tucson",
        "region": "mountain",
        "importance": 3,
        "lat": 31.8026,
        "lon": -110.9747,
        "px": 215.63,
        "py": 425.58,
        "grid_x": 27,
        "grid_y": 53,
    },
    {
        "name": "Monticello",
        "region": "mountain",
        "importance": 3,
        "lat": 37.8714,
        "lon": -109.3426,
        "px": 240.0,
        "py": 330.0,
        "grid_x": 30,
        "grid_y": 41,
    },
    {
        "name": "Ely",
        "region": "mountain",
        "importance": 3,
        "lat": 39.247,
        "lon": -114.888,
        "px": 148.0,
        "py": 280.0,
        "grid_x": 19,
        "grid_y": 39,
    },
    {
        "name": "Salt Lake City",
        "region": "mountain",
        "importance": 1,
        "lat": 39.7608,
        "lon": -111.891,
        "px": 209.97,
        "py": 244.96,
        "grid_x": 25,
        "grid_y": 30,
    },
    {
        "name": "Denver",
        "region": "mountain",
        "importance": 1,
        "lat": 37.5392,
        "lon": -104.9903,
        "px": 324.38,
        "py": 290.34,
        "grid_x": 41,
        "grid_y": 36,
    },
    {
        "name": "Colorado Springs",
        "region": "mountain",
        "importance": 3,
        "lat": 36.8339,
        "lon": -104.8214,
        "px": 327.45,
        "py": 306.96,
        "grid_x": 41,
        "grid_y": 38,
    },
    {
        "name": "Santa Fe",
        "region": "mountain",
        "importance": 3,
        "lat": 34.787,
        "lon": -105.9378,
        "px": 307.16,
        "py": 355.22,
        "grid_x": 38,
        "grid_y": 44,
    },
    {
        "name": "Casper",
        "region": "mountain",
        "importance": 3,
        "lat": 42.8501,
        "lon": -106.3252,
        "px": 310.0,
        "py": 210.0,
        "grid_x": 39,
        "grid_y": 26,
    },
    {
        "name": "Albuquerque",
        "region": "mountain",
        "importance": 3,
        "lat": 33.8844,
        "lon": -106.6504,
        "px": 294.21,
        "py": 376.5,
        "grid_x": 37,
        "grid_y": 47,
    },
    {
        "name": "Cheyenne",
        "region": "mountain",
        "importance": 2,
        "lat": 39.1,
        "lon": -104.1202,
        "px": 340.19,
        "py": 253.54,
        "grid_x": 43,
        "grid_y": 32,
    },
    {
        "name": "Pierre",
        "region": "mountain",
        "importance": 2,
        "lat": 41.9683,
        "lon": -100.35,
        "px": 408.7,
        "py": 185.92,
        "grid_x": 51,
        "grid_y": 23,
    },
    {
        "name": "Sheridan",
        "region": "mountain",
        "importance": 3,
        "lat": 42.5972,
        "lon": -106.9562,
        "px": 288.65,
        "py": 171.09,
        "grid_x": 36,
        "grid_y": 21,
    },
    {
        "name": "Minneapolis",
        "region": "midwest_north",
        "importance": 3,
        "lat": 42.9778,
        "lon": -93.265,
        "px": 537.46,
        "py": 162.12,
        "grid_x": 67,
        "grid_y": 20,
    },
    {
        "name": "Milwaukee",
        "region": "midwest_north",
        "importance": 3,
        "lat": 41.2389,
        "lon": -89.7065,
        "px": 602.12,
        "py": 203.11,
        "grid_x": 75,
        "grid_y": 25,
    },
    {
        "name": "Escanaba",
        "region": "midwest_north",
        "importance": 3,
        "lat": 45.745,
        "lon": -87.0646,
        "px": 660.0,
        "py": 190.0,
        "grid_x": 83,
        "grid_y": 24,
    },
    {
        "name": "Chicago",
        "region": "midwest_north",
        "importance": 1,
        "lat": 39.4781,
        "lon": -89.1298,
        "px": 612.6,
        "py": 244.63,
        "grid_x": 77,
        "grid_y": 31,
    },
    {
        "name": "Grand Marais",
        "region": "midwest_north",
        "importance": 3,
        "lat": 47.7504,
        "lon": -90.3345,
        "px": 563.0,
        "py": 125.0,
        "grid_x": 72,
        "grid_y": 17,
    },
    {
        "name": "Williston",
        "region": "mountain",
        "importance": 3,
        "lat": 48.1469,
        "lon": -103.618,
        "px": 350.0,
        "py": 112.0,
        "grid_x": 44,
        "grid_y": 18,
    },
    {
        "name": "Detroit",
        "region": "midwest_north",
        "importance": 2,
        "lat": 40.5314,
        "lon": -84.5458,
        "px": 695.91,
        "py": 219.79,
        "grid_x": 87,
        "grid_y": 27,
    },
    {
        "name": "Kansas City",
        "region": "midwest_central",
        "importance": 3,
        "lat": 37.0997,
        "lon": -94.5786,
        "px": 513.59,
        "py": 305.7,
        "grid_x": 64,
        "grid_y": 38,
    },
    {
        "name": "Jefferson City",
        "region": "midwest_central",
        "importance": 2,
        "lat": 38.5767,
        "lon": -92.1735,
        "px": 552.0,
        "py": 320.0,
        "grid_x": 67,
        "grid_y": 40,
    },
    {
        "name": "St. Louis",
        "region": "midwest_central",
        "importance": 2,
        "lat": 36.627,
        "lon": -90.1994,
        "px": 593.17,
        "py": 314.84,
        "grid_x": 74,
        "grid_y": 39,
    },
    {
        "name": "Springfield",
        "region": "midwest_central",
        "importance": 3,
        "lat": 39.7817,
        "lon": -89.6501,
        "px": 610.0,
        "py": 298.0,
        "grid_x": 76,
        "grid_y": 41,
    },
    {
        "name": "Indianapolis",
        "region": "midwest_central",
        "importance": 2,
        "lat": 37.9684,
        "lon": -86.6581,
        "px": 657.52,
        "py": 280.22,
        "grid_x": 82,
        "grid_y": 35,
    },
    {
        "name": "Cincinnati",
        "region": "midwest_central",
        "importance": 3,
        "lat": 37.3031,
        "lon": -84.912,
        "px": 689.25,
        "py": 295.9,
        "grid_x": 86,
        "grid_y": 37,
    },
    {
        "name": "Louisville",
        "region": "midwest_central",
        "importance": 2,
        "lat": 38.2527,
        "lon": -85.7585,
        "px": 674.0,
        "py": 314.0,
        "grid_x": 84,
        "grid_y": 39,
    },
    {
        "name": "Lincoln",
        "region": "midwest_central",
        "importance": 2,
        "lat": 40.8136,
        "lon": -96.7026,
        "px": 470.0,
        "py": 282.0,
        "grid_x": 59,
        "grid_y": 36,
    },
    {
        "name": "Columbus",
        "region": "midwest_central",
        "importance": 2,
        "lat": 38.3612,
        "lon": -83.2988,
        "px": 718.57,
        "py": 270.96,
        "grid_x": 90,
        "grid_y": 34,
    },
    {
        "name": "Omaha",
        "region": "midwest_central",
        "importance": 3,
        "lat": 39.2565,
        "lon": -95.9345,
        "px": 488.95,
        "py": 249.85,
        "grid_x": 61,
        "grid_y": 31,
    },
    {
        "name": "Topeka",
        "region": "midwest_central",
        "importance": 3,
        "lat": 39.0483,
        "lon": -95.678,
        "px": 495.0,
        "py": 315.0,
        "grid_x": 62,
        "grid_y": 40,
    },
    {
        "name": "Wichita",
        "region": "midwest_central",
        "importance": 3,
        "lat": 35.6872,
        "lon": -97.3301,
        "px": 463.58,
        "py": 334,
        "grid_x": 58,
        "grid_y": 42,
    },
    {
        "name": "Oklahoma City",
        "region": "midwest_central",
        "importance": 2,
        "lat": 35.4676,
        "lon": -97.5164,
        "px": 470.0,
        "py": 380.0,
        "grid_x": 59,
        "grid_y": 48,
    },
    {
        "name": "Tulsa",
        "region": "midwest_central",
        "importance": 3,
        "lat": 34.15398,
        "lon": -95.99277,
        "px": 487.89,
        "py": 370.15,
        "grid_x": 61,
        "grid_y": 46,
    },
    {
        "name": "Little Rock",
        "region": "midwest_central",
        "importance": 3,
        "lat": 32.7465,
        "lon": -92.2896,
        "px": 555.18,
        "py": 403.33,
        "grid_x": 69,
        "grid_y": 50,
    },
    {
        "name": "El Paso",
        "region": "southwest",
        "importance": 2,
        "lat": 31.3619,
        "lon": -107.185,
        "px": 284.49,
        "py": 435.97,
        "grid_x": 36,
        "grid_y": 54,
    },
    {
        "name": "Amarillo",
        "region": "southwest",
        "importance": 3,
        "lat": 32.7555,
        "lon": -100.3308,
        "px": 388.05,
        "py": 393.12,
        "grid_x": 51,
        "grid_y": 50,
    },
    {
        "name": "Odessa",
        "region": "southwest",
        "importance": 3,
        "lat": 31.8457,
        "lon": -102.3676,
        "px": 350.0,
        "py": 445.0,
        "grid_x": 44,
        "grid_y": 56,
    },
    {
        "name": "Wichita Falls",
        "region": "south_central",
        "importance": 3,
        "lat": 33.9137,
        "lon": -98.4934,
        "px": 445.0,
        "py": 402.0,
        "grid_x": 57,
        "grid_y": 49,
    },
    {
        "name": "Dallas",
        "region": "south_central",
        "importance": 1,
        "lat": 31.4767,
        "lon": -96.797,
        "px": 473.27,
        "py": 433.26,
        "grid_x": 59,
        "grid_y": 54,
    },
    {
        "name": "Austin",
        "region": "south_central",
        "importance": 2,
        "lat": 29.4672,
        "lon": -98.7431,
        "px": 437.91,
        "py": 480.64,
        "grid_x": 55,
        "grid_y": 60,
    },
    {
        "name": "San Angelo",
        "region": "south_central",
        "importance": 3,
        "lat": 31.4424,
        "lon": -100.4503,
        "px": 395.0,
        "py": 470.0,
        "grid_x": 49,
        "grid_y": 59,
    },
    {
        "name": "San Antonio",
        "region": "south_central",
        "importance": 3,
        "lat": 28.5241,
        "lon": -100.4936,
        "px": 406.09,
        "py": 502.87,
        "grid_x": 51,
        "grid_y": 63,
    },
    {
        "name": "Houston",
        "region": "south_central",
        "importance": 2,
        "lat": 29.1604,
        "lon": -96.3698,
        "px": 475.03,
        "py": 487.87,
        "grid_x": 60,
        "grid_y": 61,
    },
    {
        "name": "Galveston",
        "region": "south_central",
        "importance": 3,
        "lat": 29.3013,
        "lon": -94.7977,
        "px": 485.0,
        "py": 504.0,
        "grid_x": 63,
        "grid_y": 64,
    },
    {
        "name": "Jackson",
        "region": "south_central",
        "importance": 2,
        "lat": 31.0288,
        "lon": -90.1848,
        "px": 593.43,
        "py": 443.82,
        "grid_x": 74,
        "grid_y": 55,
    },
    {
        "name": "New Orleans",
        "region": "south_central",
        "importance": 3,
        "lat": 29.2511,
        "lon": -90.6715,
        "px": 584.59,
        "py": 485.73,
        "grid_x": 73,
        "grid_y": 61,
    },
    {
        "name": "Baton Rouge",
        "region": "south_central",
        "importance": 2,
        "lat": 30.4515,
        "lon": -91.1871,
        "px": 565.0,
        "py": 470.0,
        "grid_x": 71,
        "grid_y": 59,
    },
    {
        "name": "Memphis",
        "region": "south_central",
        "importance": 3,
        "lat": 33.1495,
        "lon": -90.049,
        "px": 595.9,
        "py": 393.83,
        "grid_x": 74,
        "grid_y": 49,
    },
    {
        "name": "Nashville",
        "region": "southeast",
        "importance": 2,
        "lat": 36.1627,
        "lon": -86.7816,
        "px": 648.0,
        "py": 360.0,
        "grid_x": 81,
        "grid_y": 45,
    },
    {
        "name": "Atlanta",
        "region": "southeast",
        "importance": 1,
        "lat": 32.749,
        "lon": -84.388,
        "px": 698.78,
        "py": 403.27,
        "grid_x": 87,
        "grid_y": 50,
    },
    {
        "name": "Augusta",
        "region": "northeast",
        "importance": 3,
        "lat": 44.3106,
        "lon": -69.7795,
        "px": 900.0,
        "py": 150.0,
        "grid_x": 112,
        "grid_y": 19,
    },
    {
        "name": "Montgomery",
        "region": "southeast",
        "importance": 3,
        "lat": 31.3792,
        "lon": -86.3077,
        "px": 663.89,
        "py": 435.56,
        "grid_x": 83,
        "grid_y": 54,
    },
    {
        "name": "Birmingham",
        "region": "southeast",
        "importance": 3,
        "lat": 33.5186,
        "lon": -86.8104,
        "px": 654.0,
        "py": 412.0,
        "grid_x": 84,
        "grid_y": 52,
    },
    {
        "name": "Charlotte",
        "region": "southeast",
        "importance": 3,
        "lat": 34.4271,
        "lon": -80.8431,
        "px": 763.2,
        "py": 363.71,
        "grid_x": 95,
        "grid_y": 45,
    },
    {
        "name": "Raleigh",
        "region": "southeast",
        "importance": 3,
        "lat": 34.9796,
        "lon": -79.6382,
        "px": 785.09,
        "py": 350.68,
        "grid_x": 98,
        "grid_y": 44,
    },
    {
        "name": "Jacksonville",
        "region": "southeast",
        "importance": 2,
        "lat": 30.3322,
        "lon": -81.6557,
        "px": 748.43,
        "py": 460.25,
        "grid_x": 94,
        "grid_y": 58,
    },
    {
        "name": "Tallahassee",
        "region": "southeast",
        "importance": 2,
        "lat": 30.4383,
        "lon": -84.2807,
        "px": 700.0,
        "py": 472.0,
        "grid_x": 88,
        "grid_y": 59,
    },
    {
        "name": "Orlando",
        "region": "southeast",
        "importance": 3,
        "lat": 28.5383,
        "lon": -81.3792,
        "px": 752.0,
        "py": 500.0,
        "grid_x": 93,
        "grid_y": 63,
    },
    {
        "name": "Tampa",
        "region": "southeast",
        "importance": 2,
        "lat": 27.9506,
        "lon": -82.4572,
        "px": 733.86,
        "py": 516.4,
        "grid_x": 92,
        "grid_y": 65,
    },
    {
        "name": "Miami",
        "region": "southeast",
        "importance": 1,
        "lat": 25.7617,
        "lon": -80.1918,
        "px": 775.03,
        "py": 568,
        "grid_x": 97,
        "grid_y": 71,
    },
    {
        "name": "Pittsburgh",
        "region": "northeast",
        "importance": 3,
        "lat": 38.7406,
        "lon": -80.3959,
        "px": 771.32,
        "py": 262.01,
        "grid_x": 96,
        "grid_y": 33,
    },
    {
        "name": "Cleveland",
        "region": "northeast",
        "importance": 3,
        "lat": 39.8993,
        "lon": -82.4944,
        "px": 733.19,
        "py": 234.7,
        "grid_x": 92,
        "grid_y": 29,
    },
    {
        "name": "Buffalo",
        "region": "northeast",
        "importance": 3,
        "lat": 41.0864,
        "lon": -80.4784,
        "px": 769.82,
        "py": 206.71,
        "grid_x": 96,
        "grid_y": 26,
    },
    {
        "name": "Albany",
        "region": "northeast",
        "importance": 3,
        "lat": 41.2526,
        "lon": -76.2562,
        "px": 846.55,
        "py": 202.79,
        "grid_x": 106,
        "grid_y": 25,
    },
    {
        "name": "New York",
        "region": "northeast",
        "importance": 1,
        "lat": 40.1128,
        "lon": -76.006,
        "px": 851.1,
        "py": 229.66,
        "grid_x": 106,
        "grid_y": 29,
    },
    {
        "name": "Philadelphia",
        "region": "northeast",
        "importance": 2,
        "lat": 39.0526,
        "lon": -76.2652,
        "px": 846.39,
        "py": 254.66,
        "grid_x": 106,
        "grid_y": 32,
    },
    {
        "name": "Baltimore",
        "region": "northeast",
        "importance": 3,
        "lat": 38.2904,
        "lon": -77.9122,
        "px": 816.46,
        "py": 272.63,
        "grid_x": 102,
        "grid_y": 34,
    },
    {
        "name": "Washington",
        "region": "northeast",
        "importance": 1,
        "lat": 37.7072,
        "lon": -78.2369,
        "px": 810.56,
        "py": 286.38,
        "grid_x": 101,
        "grid_y": 36,
    },
    {
        "name": "Boston",
        "region": "northeast",
        "importance": 2,
        "lat": 41.3601,
        "lon": -73.0589,
        "px": 904.65,
        "py": 200.26,
        "grid_x": 113,
        "grid_y": 25,
    },
    {
        "name": "Concord",
        "region": "northeast",
        "importance": 3,
        "lat": 43.2081,
        "lon": -71.5376,
        "px": 888.0,
        "py": 176.0,
        "grid_x": 111,
        "grid_y": 22,
    },
    {
        "name": "Richmond",
        "region": "northeast",
        "importance": 2,
        "lat": 37.5407,
        "lon": -77.436,
        "px": 800.0,
        "py": 320.0,
        "grid_x": 100,
        "grid_y": 40,
    },
    {
        "name": "Columbia",
        "region": "southeast",
        "importance": 2,
        "lat": 34.0007,
        "lon": -81.0348,
        "px": 755.0,
        "py": 388.0,
        "grid_x": 93,
        "grid_y": 51,
    },
]



def register_city_seed_commands(app):
    @app.cli.command("seed-cities")
    def seed_cities():
        """Seed regions and cities for the map."""
        print("Seeding regions & cities...")

        # Regions
        region_cache = {}
        for code, name in REGIONS.items():
            region = Region.query.filter_by(code=code).first()
            if not region:
                region = Region(code=code, name=name)
                db.session.add(region)
            region_cache[code] = region

        db.session.flush()  # ať mají regiony id

        # Cities
        for data in CITIES:
            city = City.query.filter_by(name=data["name"]).first()
            if not city:
                city = City(name=data["name"])
                db.session.add(city)

            city.region = region_cache[data["region"]]
            city.importance = data["importance"]
            city.lat = data["lat"]
            city.lon = data["lon"]
            city.px = data["px"]
            city.py = data["py"]
            city.grid_x = data["grid_x"]
            city.grid_y = data["grid_y"]
            state_info = STATE_MAP.get(city.name)
            if state_info:
                city.state, city.state_shortcut = state_info
            else:
                city.state = None
                city.state_shortcut = None

            # doplníme popis z mapy, pokud je k dispozici
            desc = DESCRIPTION_MAP.get(city.name)
            if desc:
                city.description = desc

        db.session.commit()
        print("✅ Seed hotový")
