# cities_seed.py

from models import db
from models.region import Region
from models.city import City

REGIONS = {
    "pacific_northwest": "Pacific Northwest",
    "pacific_southwest": "Pacific Southwest",
    "mountain": "Mountain",
    "midwest_north": "Midwest North",
    "midwest_central": "Midwest Central",
    "southwest": "Southwest",
    "south_central": "South Central",
    "southeast": "Southeast",
    "northeast": "Northeast",
}

STATE_MAP = {
    "Seattle": ("Washington", "WA"),
    "Portland": ("Oregon", "OR"),
    "Spokane": ("Washington", "WA"),
    "Olympia": ("Washington", "WA"),
    "Salem": ("Oregon", "OR"),
    "Astoria": ("Oregon", "OR"),
    "Boise": ("Idaho", "ID"),
    "Helena": ("Montana", "MT"),
    "Bismarck": ("North Dakota", "ND"),
    "San Francisco": ("California", "CA"),
    "Oakland": ("California", "CA"),
    "San Jose": ("California", "CA"),
    "Sacramento": ("California", "CA"),
    "Fresno": ("California", "CA"),
    "Bakersfield": ("California", "CA"),
    "Los Angeles": ("California", "CA"),
    "San Diego": ("California", "CA"),
    "Eureka": ("California", "CA"),
    "Las Vegas": ("Nevada", "NV"),
    "Phoenix": ("Arizona", "AZ"),
    "Tucson": ("Arizona", "AZ"),
    "Salt Lake City": ("Utah", "UT"),
    "Denver": ("Colorado", "CO"),
    "Colorado Springs": ("Colorado", "CO"),
    "Santa Fe": ("New Mexico", "NM"),
    "Albuquerque": ("New Mexico", "NM"),
    "Cheyenne": ("Wyoming", "WY"),
    "Pierre": ("South Dakota", "SD"),
    "Sheridan": ("Wyoming", "WY"),
    "Minneapolis": ("Minnesota", "MN"),
    "Milwaukee": ("Wisconsin", "WI"),
    "Chicago": ("Illinois", "IL"),
    "Detroit": ("Michigan", "MI"),
    "Kansas City": ("Missouri", "MO"),
    "St. Louis": ("Missouri", "MO"),
    "Indianapolis": ("Indiana", "IN"),
    "Cincinnati": ("Ohio", "OH"),
    "Columbus": ("Ohio", "OH"),
    "Omaha": ("Nebraska", "NE"),
    "Wichita": ("Kansas", "KS"),
    "Tulsa": ("Oklahoma", "OK"),
    "Oklahoma City": ("Oklahoma", "OK"),
    "Little Rock": ("Arkansas", "AR"),
    "El Paso": ("Texas", "TX"),
    "Amarillo": ("Texas", "TX"),
    "Dallas": ("Texas", "TX"),
    "Austin": ("Texas", "TX"),
    "San Antonio": ("Texas", "TX"),
    "Houston": ("Texas", "TX"),
    "Wichita Falls": ("Texas", "TX"),
    "Galveston": ("Texas", "TX"),
    "Odessa": ("Texas", "TX"),
    "San Angelo": ("Texas", "TX"),
    "Grand Marais": ("Minnesota", "MN"),
    "Escanaba": ("Michigan", "MI"),
    "Casper": ("Wyoming", "WY"),
    "Monticello": ("Utah", "UT"),
    "Ely": ("Nevada", "NV"),
    "Williston": ("North Dakota", "ND"),
    "Jackson": ("Mississippi", "MS"),
    "New Orleans": ("Louisiana", "LA"),
    "Memphis": ("Tennessee", "TN"),
    "Atlanta": ("Georgia", "GA"),
    "Augusta": ("Maine", "ME"),
    "Montgomery": ("Alabama", "AL"),
    "Charlotte": ("North Carolina", "NC"),
    "Raleigh": ("North Carolina", "NC"),
    "Jacksonville": ("Florida", "FL"),
    "Tampa": ("Florida", "FL"),
    "Miami": ("Florida", "FL"),
    "Pittsburgh": ("Pennsylvania", "PA"),
    "Cleveland": ("Ohio", "OH"),
    "Buffalo": ("New York", "NY"),
    "Albany": ("New York", "NY"),
    "New York": ("New York", "NY"),
    "Philadelphia": ("Pennsylvania", "PA"),
    "Baltimore": ("Maryland", "MD"),
    "Washington": ("District of Columbia", "DC"),
    "Boston": ("Massachusetts", "MA"),
    "Concord": ("New Hampshire", "NH"),
    "Richmond": ("Virginia", "VA"),
    "Columbia": ("South Carolina", "SC"),
    "Birmingham": ("Alabama", "AL"),
    "Baton Rouge": ("Louisiana", "LA"),
    "Tallahassee": ("Florida", "FL"),
    "Orlando": ("Florida", "FL"),
    "Nashville": ("Tennessee", "TN"),
    "Springfield": ("Illinois", "IL"),
    "Jefferson City": ("Missouri", "MO"),
    "Topeka": ("Kansas", "KS"),
    "Lincoln": ("Nebraska", "NE"),
    "Louisville": ("Kentucky", "KY"),
}

DESCRIPTION_MAP = {
    "Seattle": "Přístavní metropole Pacifiku.\nMěsto technologických gigantů a kaváren.\nDeštivá kulisa s výhledem na Mt. Rainier.",
    "Portland": "Město mostů a řeky Willamette.\nZnámé craft pivem a food-trucky.\nZelené parky, cyklo kultura a klidný vibe.",
    "Seattle": "Přístavní metropole Pacifiku a jedno z nejdynamičtějších měst severozápadu.\nDomov technologických gigantů, živé hudební scény a nekonečných kavárenských rituálů.\nDeštivá kulisa dodává městu lehce melancholický filmový nádech.\nKdyž se počasí vyjasní, nad městem majestátně vystupuje Mt. Rainier jako obří strážce regionu.\nSeattle je rodištěm grunge a kapel jako Nirvana či Pearl Jam.\nZajímavostí je, že zde vznikl i světový fenomén Starbucks.\nMěsto spojuje přírodu, inovace a kreativitu způsobem, který nikde jinde nenajdeš.\nVášniví cestovatelé tu ocení propojení města s horami, ostrovy i oceánem.",
    "Portland": "Město mostů, řeky Willamette a neformální atmosféry založené na kreativitě a komunitě.\nPortland je známý craft pivovary, food-trucky a silnou cyklistickou kulturou.\nPůsobí jako zelený ostrov plný parků, stromových alejí a městských zahrad.\nZajímavostí je, že se zde nachází největší nezávislé knihkupectví na světě – Powell's.\nMístní scéna je bohémská, hravá a přívětivá k experimentům.\nVe čtvrtích jako Alberta Arts District najdeš barvy, hudbu i autentický street art.\nMěsto je klidné, osobité a přitahuje všechny, kteří chtějí žít pomaleji.\nV Portlandu se tradice a moderní městský život prolínají v překvapivé harmonii.",
    "Spokane": "Východní metropole Washingtonu ležící na malebné řece Spokane.\nHistorické mlýny a staré továrny připomínají časy, kdy město táhl průmysl.\nDnes je Spokane vstupní branou do divočiny Inland Empire.\nMěsto má překvapivě živou kulturní scénu kolem divadel, galerií a festivalů.\nRiverfront Park s ikonickou pavoučí sochou je srdcem městského života.\nZajímavostí je, že Spokane hostilo EXPO 1974 jako první ekologickou světovou výstavu.\nOkolní hory lákají na trailrunning, lyžování a outdoorové výpravy.\nJde o město, kde se historie setkává s moderním pojetím maloměstské pohody.",
    "Olympia": "Hlavní město státu Washington situované u vod Puget Sound.\nOlympia má kompaktní downtown s ikonickým Capitolem a příjemnou přístavní promenádou.\nAtmosféra je klidná, občanská a silně umělecká.\nMěsto je známé komunitní podporou lokálních podniků a ekologických iniciativ.\nZajímavostí je, že právě Olympia byla zázemím vlivné indie hudební scény 90. let.\nV okolí začínají brány k Olympic National Park, jednomu z nejpestřejších ekosystémů USA.\nPromenády a parky působí téměř lázeňským dojmem.\nOlympia je ideální zastávkou mezi Seattlem, horami a pobřežní divočinou.",
    "Salem": "Hlavní město Oregonu ležící v zemědělsky bohatém údolí Willamette.\nHistorické ulice a státní úřady vytvářejí kultivovanou atmosféru menší metropole.\nMěsto je obklopeno vinicemi, farmami a klidnou krajinou.\nSalem je znám svou pohodou, slabším tempem a vysokou kvalitou života.\nStátní Capitol s výraznou zlato-zelenou kupolí patří mezi nejfotografovanější budovy Oregonu.\nZajímavostí je, že právě zde probíhá jeden z největších květinových festivalů na západním pobřeží.\nSalem je přátelské město, které kombinuje historii, kulturu a klid.\nJe ideálním výchozím bodem pro výlety do vinic i k oceánu.",
    "Astoria": "Historické pobřežní město u ústí řeky Columbia.\nJe nejstarším americkým městem na západním pobřeží se souvislým osídlením.\nStrmé ulice, dřevěné domy a mlžná rána vytvářejí působivou filmovou kulisu.\nMost Astoria–Megler je ikonickou dominantou a jedním z nejdelších trámových mostů světa.\nZajímavostí je, že zde bylo natáčeno několik kultovních filmů, včetně Goonies.\nMěsto má bohatou námořní a rybářskou historii.\nKopce kolem města nabízejí dechberoucí výhledy na Pacifik.\nAstoria působí jako místo, kde čas plyne pomaleji a kde mlha dodává ulicím tajemství.",
    "Boise": "Horská metropole Idaha zasazená do údolí Treasure Valley.\nMěsto má příjemně moderní vibe propojený s přírodou a univerzitním životem.\nBoise River Greenbelt patří mezi nejhezčí městské parky v USA.\nTrailová kultura je zde velmi silná – cyklisté a běžci mají k dispozici desítky kilometrů stezek.\nZajímavostí je, že Boise má největší komunitu Basků v Severní Americe.\nSlunné podnebí a čistý vzduch vytvářejí skvělou atmosféru.\nKombinace technologií, sportu a studentského života dodává městu dynamiku.\nBoise funguje jako vstupní brána do hor Sawtooth a divočiny Idaha.",
    "Helena": "Kapitál Montany zasazený do podhůří mezi skalami a borovicemi.\nMěsto si zachovalo šarm zlatokopecké éry, která formovala jeho centrum.\nArchitektura Capitolu a staré ulice působí historicky a přívětivě.\nZajímavostí je, že Helena bývala jedním z nejbohatších měst USA díky zlatým nalezištím.\nOkolní krajina nabízí nespočet výletů k jezerům, hřebenům a vyhlídkám.\nMěsto má také nečekaně silnou galerijní a uměleckou scénu.\nHelena kombinuje ticho divočiny s kultivovaným městským prostředím.\nJe ideální zastávkou pro všechny, kteří hledají klid i dobrodružství.",
    "Bismarck": "Hlavní město Severní Dakoty ležící na řece Missouri.\nMěsto má široké bulváry a uvolněnou atmosféru Velkých plání.\nJe centrem energetického boomu Bakken Basin.\nZajímavostí je, že státní Capitol v Bismarcku je jediným mrakodrapovým Capitolem v USA.\nMístní historie je úzce spojená s původními obyvateli a řekou Missouri.\nOkolní prérie vytvářejí nekonečná otevřená panoramata.\nMěsto působí klidně, stabilně a má dlouhou správní tradici.\nBismarck je ideální základnou pro poznávání severních plání a Missouri River.",
    "Oakland": "Hlavní přístav regionu East Bay a jedno z kulturně nejpestřejších měst Kalifornie.\nOakland je domovem živé hudební, street art a food scény.\nHistorické sklady a industriální čtvrti se proměnily v moderní kreativní centra.\nZajímavostí je, že Oakland má více slunečných dní než San Francisco.\nFox Theater a Lake Merritt patří mezi nejznámější městské symboly.\nKomunity zde mají silnou identitu a hrdost na místní historii.\nZ Oaklandu jsou jedny z nejlepších výhledů na San Francisco skyline.\nMěsto působí drsně, autenticky a zároveň neskutečně živě.",
    "San Jose": "Srdce Silicon Valley a jedno z nejrychleji rostoucích technologických center světa.\nMěsto je domovem inovací, startupů a moderních kampusů firem jako Apple či Google.\nNa první pohled působí jako klidné slunné předměstí, ale uvnitř tepe vysoké tempo vývoje.\nHistorické centrum kolem San Pedro Square dodává metropoli příjemný komunitní charakter.\nZajímavostí je, že San Jose je třetím největším městem Kalifornie.\nOkolní kopce Santa Clara Valley nabízejí krásné výhledy a trailové trasy.\nMěsto je kosmopolitní, bezpečné a neustále se rozvíjí.\nSan Jose propojuje moderní technologie, multikulturní atmosféru a pohodový životní styl.",
    "Sacramento": "Kapitál Kalifornie ležící na soutoku řek Sacramento a American River.\nMěsto je pevně spojené s historií zlaté horečky a starými železničními tratěmi.\nDowntown kombinuje státní správu, restaurace a historické čtvrti Old Sacramento.\nZajímavostí je, že Sacramento má jednu z nejlepších farm-to-fork gastronomických scén v USA.\nŽivot zde plyne pomaleji než v pobřežních metropolích.\nPřesto jde o jedno z nejrychleji rostoucích měst Kalifornie.\nHorká léta, vodní aktivity a stinné aleje dodávají městu charakter.\nSacramento spojuje historii, politiku a přístupnost přírody.",
    "Fresno": "Brána do úrodného údolí San Joaquin a jedno z největších zemědělských center USA.\nLokalita je strategická – blízko Yosemite, Sequoia a Kings Canyon National Park.\nMěsto má přímou, praktickou atmosféru a široké ulice typické pro centrální Kalifornii.\nZajímavostí je, že okolní region produkuje většinu mandlí a mnoho plodin pro celý svět.\nFresno se rychle rozvíjí díky studentům, imigrantům a logistickým firmám.\nV létě je zde velmi horko, což formuje místní rytmus života.\nStarší části města nabízejí historické domy a příjemné parky.\nFresno je kombinací zemědělské síly, rodinného života a přístupu do národních parků.",
    "Bakersfield": "Agro, energie a country hudba – to je Bakersfield, metropole kalifornského středozápadu.\nMěsto leží v srdci údolí San Joaquin a je významným ropným i zemědělským uzlem.\nHudební scéna zde zrodila slavný Bakersfield Sound, který změnil country žánr.\nZajímavostí je, že region produkuje enormní množství potravin pro USA i svět.\nMěsto má suché horké klima a průhlednou oblohu většinu roku.\nBakersfield působí přímočaře, ale skrývá řadu kulturních festivalů a komunit.\nDálnice zde tvoří tepny spojující LA, Fresno a Sierra Nevada.\nJe to místo se silnou identitou, které kombinuje lavor dějin, hudby a průmyslu.",
    "Los Angeles": "Rozlehlá metropole filmového průmyslu a jedno z nejznámějších měst světa.\nLA zahrnuje desítky odlišných čtvrtí – od Hollywoodu po Venice Beach.\nMěsto je ikonou popkultury, médií, influencerů a mezinárodního mixu kultur.\nZajímavostí je, že Los Angeles nemá klasické centrum – život se rozlévá do šířky.\nAutentické taquerie, filmové studia a palmové bulváry tvoří unikátní koláž.\nDálnice tvoří nekonečnou síť, která definuje rytmus celého regionu.\nKopce Santa Monica Mountains nabízejí výhledy na oceán i město.\nLA je místem snů, kontrastů a nekonečné kreativity.",
    "San Diego": "Slunné město na jihu Kalifornie známé svým stabilním podnebím a pohodou.\nSan Diego je domovem námořních základen, surfové kultury a světově známé zoo.\nPobřeží nabízí dlouhé promenády, útesy i klidné písečné pláže.\nZajímavostí je, že město má jeden z nejmilejších a nejstálejších klimat na světě.\nDowntown kombinuje historické Gaslamp Quarter s moderním bayfrontem.\nKultura je ovlivněna blízkostí Mexika – jídlo je zde fantastické.\nSan Diego působí přátelsky, otevřeně a letně po celý rok.\nJe ideální destinací pro život venku a námořní atmosféru.",
    "Eureka": "Pobřežní město sevřené mezi Pacifikem a obřími sekvojovými lesy.\nHistorické viktoriánské centrum patří mezi nejlépe dochovaná na západním pobřeží.\nMěsto má silné kořeny v rybářské a námořní historii.\nZajímavostí je, že v okolí roste jedny z nejvyšších stromů planety – Redwoody.\nMlhy a chladné počasí dávají Eurece tajemný, až romanticky melancholický nádech.\nPřístav je plný rybářských lodí a industriálních struktur.\nKultura je zde alternativní, komunitní a silně spojená s přírodou.\nEureka působí jako brána do surové severokalifornské divočiny.",
    "Las Vegas": "Pouštní město neonů, kasin a nikdy nekončící zábavy.\nLas Vegas Strip září po celou noc a nabízí show, hotely i extrémní architekturu.\nZa rohem však začíná tiché a krásné skalní prostředí Mojave Desert.\nZajímavostí je, že většina ikonických staveb vyrostla během neuvěřitelně krátkých období.\nVegas je symbolem amerických snů, risku a neskutečné energie.\nKdyž světla města zhasnou, poušť kolem je tichá a hvězdná.\nRed Rock Canyon je jen několik minut od města.\nVegas je kontrast mezi lidskou fantazií a syrovou pouští.",
    "Phoenix": "Rozlehlá metropole Arizony rozprostřená v široké Sonorské poušti.\nHorká léta patří k nejintenzivnějším v USA a formují zdejší životní styl.\nMěsto má silné sportovní zázemí, golfová hřiště a moderní technologické parky.\nZajímavostí je, že Phoenix je jedním z nejrychleji rostoucích měst Ameriky.\nPůvodní kultury a mexický vliv jsou cítit v architektuře i gastronomii.\nBouře monzunů přinášejí v létě dramatická nebe plná blesků.\nOkolní poušť nabízí nádherné západy slunce a ikonické saguaro kaktusy.\nPhoenix kombinuje surové klima, moderní ekonomiku a energickou populaci.",
    "Tucson": "Pouštní město obklopené pohořím Santa Catalina a obřími saguaro kaktusy.\nTucson má silnou univerzitní atmosféru a živou hispánskou kulturu.\nNoční obloha zde patří k nejtmavším v USA, ideální pro astronomy.\nZajímavostí je, že Tucson aktivně chrání tmu zavedením omezení světelného smogu.\nMěsto je klidnější než Phoenix, ale působí autentičtěji a kulturně pestře.\nHistorické čtvrti mají adobe architekturu a barevné ulice.\nOkolní poušť je plná života – od javelin až po kojoty.\nTucson nabízí kombinaci tradic, přírody a studentské energie.",
    "Salt Lake City": "Metropole Utahu ležící mezi Wasatch Range a Great Salt Lake.\nMěsto je známé čistými ulicemi, moderním downtownem a silnou zimní sportovní tradicí.\nPůsobí jako brána do hor plných ski resortů a národních parků.\nZajímavostí je, že Salt Lake City hostilo zimní olympijské hry 2002 a usiluje o jejich návrat.\nMístní architektura je směsí moderny a monumentálních náboženských staveb.\nKultura je zde překvapivě pestrá a ovlivněná přistěhovalci z celého světa.\nOkolní hory nabízejí jedny z nejlepších sněhových podmínek v USA.\nSalt Lake City spojuje městský život, sport a divokou krajinu na dosah ruky.",
    "Denver": "Mílové město na úpatí Skalistých hor s energickou atmosférou a rychlým růstem.\nDenver má silnou pivní scénu, sportovní kulturu a moderní tech sektor.\nHistorické čtvrti jako LoDo míchají staré sklady s novými bary a restauracemi.\nZajímavostí je, že Denver má více než 300 slunečných dní ročně.\nMěsto je strategickou bránou do hor, národních parků a ski resortů Colorada.\nVzduch je zde čistý a suchý, což dodává městu vysokohorský charakter.\nDenver stále roste a přitahuje mladé profesionály z celé země.\nJe to město, kde se urbanismus a příroda přirozeně doplňují.",
    "Colorado Springs": "Město ležící pod ikonickým Pikes Peak a součást Front Range.\nColorado Springs je známé vojenskými akademiemi, olympijskými centry a nádhernou přírodou.\nGarden of the Gods s červenými skalami patří mezi nejkrásnější přírodní parky USA.\nZajímavostí je, že právě zde vzniklo moderní americké sportovní tréninkové centrum.\nMěsto má klidnější atmosféru než Denver a působí rodinněji.\nKombinace hor, náhorních plošin a modré oblohy vytváří působivé scenérie.\nNajdeš tu mix outdoorových nadšenců a vojenské komunity.\nColorado Springs spojuje majestátní přírodu s poklidným městským rytmem.",
    "Santa Fe": "Jedno z nejstarších měst USA, známé svou adobe architekturou a uměleckou scénou.\nSanta Fe má silnou tradici galerií, muzeí a kulturních festivalů.\nHistorické centrum působí unikátně – každá budova dýchá jihozápadním stylem.\nZajímavostí je, že město leží ve vysoké nadmořské výšce přes 2100 metrů.\nSanta Fe je gastronomickou metropolí chilies a tradičních pokrmů Nového Mexika.\nHorské okolí poskytuje chladnější klima než zbytek regionu.\nAtmosféra je klidná, spirituální a kreativní.\nSanta Fe je magnetem pro umělce, cestovatele a milovníky historie.",
    "Albuquerque": "Balónové město ležící na březích Rio Grande.\nMěsto je známé svým každoročním Balloon Fiesta, největší balónovou akcí na světě.\nMix kultur – původní obyvatelé, hispánská tradice a americký západ – je zde velmi silný.\nZajímavostí je, že Albuquerque bylo jednou z hlavních scén seriálu Breaking Bad.\nSuché klima a výhled na Sandia Mountains vytvářejí ikonickou siluetu.\nRoute 66 dodává ulicím retro atmosféru.\nMěsto nabízí skvělé jídlo – zejména červené a zelené chile.\nAlbuquerque je klidné, slunečné a překvapivě přátelské.",
    "Cheyenne": "Kovbojské hlavní město Wyomingu s dlouhou tradicí rodea.\nCheyenne Frontier Days jsou jednou z největších westernových akcí světa.\nMěsto má silné železniční dědictví a historické budovy z dob osidlování.\nZajímavostí je, že Cheyenne bývalo jedním z nejbohatších měst západu díky železnici.\nAtmosféra je otevřená, větrná a typicky prérijní.\nMístní komunita drží silné tradice a patriotismus.\nOkolní krajina nabízí nekonečné horizonty a ticho Velkých plání.\nCheyenne spojuje starý západ s moderním maloměstským rytmem.",
    "Pierre": "Malý kapitál Jižní Dakoty ležící na řece Missouri.\nMěsto působí velmi poklidně a správně – je centrem státní administrativy.\nPierre je obklopené rovinami, jezery a otevřenou krajinou Dakoty.\nZajímavostí je, že jde o jedno z nejmenších hlavních měst USA podle populace.\nCapitol má elegantní kupoli a krásné zahrady.\nAtmosféra je přátelská a nenápadná.\nMěsto slouží jako zázemí pro rybaření, lov a outdoor.\nPierre představuje čistou esenci prérijního života.",
    "Sheridan": "Město pod Bighorn Mountains s bohatým westernovým dědictvím.\nHistorické saloony a staré ulice připomínají období rančerské kultury.\nMístní komunita si hrdě uchovává tradice amerického západu.\nZajímavostí je, že zde často pobýval spisovatel Ernest Hemingway.\nSheridan je vstupní branou do krásných trailů a horských cest.\nAtmosféra je klidná, přátelská a autentická.\nKombinace historie, hor a otevřených plání je unikátní.\nMěsto je ideální základnou pro dobrodružství v Bighorn National Forest.",
    "Minneapolis": "Město jezer, cyklostezek a moderní architektury.\nMinneapolis tvoří spolu se Saint Paul dvojměstí Twin Cities.\nMěsto má silnou hudební tradici – zejména díky ikoně jménem Prince.\nZajímavostí je, že Minneapolis má jednu z největších sítí městských parků v USA.\nZimy jsou zde drsné, ale místní je berou jako součást identity.\nKultura je rozmanitá a spojena s mnoha divadly a galeriemi.\nMosty přes Mississippi dodávají městu vizuální dynamiku.\nMinneapolis je čisté, zelené a energické město severu.",
    "Milwaukee": "Pivní metropole na břehu Michiganského jezera s bohatou industriální historií.\nMěsto je domovem Harley-Davidson a tradičních německých i českých komunit.\nPobřežní promenády lákají na sport i relax.\nZajímavostí je, že Milwaukee má více festivalů, než bys čekal – léto je tu velmi živé.\nHistorické pivovary dodávají městu autentický charakter.\nLokální gastronomie kombinuje pivo, sýry a středoevropské chutě.\nMěsto má příjemnou, lehce nostalgickou atmosféru.\nMilwaukee působí jako industriální srdce Velkých jezer.",
    "Tulsa": "Art Deco perla Oklahomy s bohatou ropnou historií.\nCentrum města je plné nádherných budov z éry prosperity 20. let.\nTulsa má živou hudební scénu a bluesové kořeny.\nZajímavostí je, že zde vznikl fenomenální park Gathering Place oceňovaný po celém světě.\nMěsto leží na Route 66 a nese její retro atmosféru.\nNové parky a promenády kolem Arkansas River oživují centrum.\nTulsa kombinuje historii, eleganci a moderní rozvoj.\nJe to místo s charismatem a silnou kulturní identitou.",    
    "Oklahoma City": "Hlavní město Oklahomy ležící u řeky North Canadian.\nMěsto kombinuje moderní downtown s cowboy tradicemi a průmyslovými kořeny.\nBricktown je dnes živou čtvrtí plnou restaurací, kanálů a hudby.\nZajímavostí je, že OKC má jednu z nejaktivnějších bouřkových oblastí na světě.\nCapitol je unikátní tím, že má umístěnou ropnou věž přímo v areálu.\nNBA tým Thunder dodává městu sportovní energii.\nAtmosféra je přátelská a otevřená, typická pro Jihozápad.\nOklahoma City je dynamická metropole, která spojuje historii, moderní průmysl i kulturu.",
    "Little Rock": "Kapitál Arkansasu ležící na řece Arkansas.\nMěsto je známé svou rolí v hnutí za občanská práva a historickou školní integrací.\nDowntown nabízí mix muzeí, mostů a promenád.\nZajímavostí je, že v Little Rock se nachází prezidentská knihovna Billa Clintona.\nBlízké Ozark Mountains dávají oblasti atraktivní přírodní rámec.\nAtmosféra je klidná, jižanská a komunitní.\nMěsto spojuje historii, kulturu a přírodu dohromady.\nLittle Rock působí jako příjemná rovnováha mezi městským životem a venkovským okolím.",
    "El Paso": "Hraniční město na řece Rio Grande, přirozeně propojené s mexickým Ciudad Juárez.\nEl Paso má silnou hispánskou kulturu a jedinečné pouštní prostředí.\nPohoří Franklin Mountains dodává městu dramatickou kulisu.\nZajímavostí je, že oblast patří mezi nejbezpečnější velká města USA.\nKuchyně je zde výrazně tex-mex a plná autentických chutí.\nMístní tradice spojují americkou a mexickou identitu.\nSlunné a suché klima vytváří příjemnou atmosféru většinu roku.\nEl Paso je kulturní křižovatkou Západu a Latinské Ameriky.",
    "Amarillo": "Prérijní město Texasu ležící na legendární dálnici I-40.\nMísto je známé ikonickým Cadillac Ranchem, kde auta trčí z pouště jako sochy.\nAmarillo má silné rančerské tradice a typickou západní atmosféru.\nZajímavostí je, že zde najdeš Big Texan Steak Ranch, proslulý obřím steakem.\nKrajina je plná dálav, větru a nekonečných horizontů.\nAtmosféra je otevřená, drsná a pravověrně texaská.\nOkolní kaňony, jako Palo Duro, jsou překvapivě malebné.\nAmarillo je vstupní branou do panhandle oblasti a starého západu.",
    "Dallas": "Moderní metropole severního Texasu s výrazným skyline plným mrakodrapů.\nMěsto je známé financemi, sportovními kluby a bohatou obchodní historií.\nDallas má silné zázemí v technologiích, energetice i dopravě.\nZajímavostí je, že město má jednu z největších městských uměleckých čtvrtí v USA.\nDallas Cowboys patří mezi nejslavnější sportovní značky světa.\nDowntown je plný muzeí, parků a nových rezidenčních projektů.\nDálnice vytvářejí síť spojující město se zbytkem Texasu.\nDallas je rychle rostoucí metropole plná ambicí a moderního stylu.",
    "Austin": "Hlavní město Texasu a jedno z nejrychleji rostoucích měst USA.\nAustin je známý jako světová metropole živé hudby a domov festivalů SXSW.\nTech firmy zde vytvářejí dynamickou a inovativní atmosféru.\nZajímavostí je, že město má vlastní slogan „Keep Austin Weird“, který podporuje kreativitu.\nLady Bird Lake a okolní zelené pásy jsou ideální pro běh, paddleboard i cyklistiku.\nNoční život je pestrý, od rockových klubů po tiché bary s výhledem na řeku.\nMěsto láká umělce, programátory i studenty z celého světa.\nAustin propojuje kulturu, přírodu a moderní velkoměstský styl.",
    "San Antonio": "Historické město s bohatým hispánským dědictvím a ikonou Alamo.\nSan Antonio je známé svou krásnou River Walk – promenádou lemovanou restauracemi a mosty.\nKultura je zde hluboce zakořeněná v tradicích a festivalech.\nZajímavostí je, že San Antonio má největší vojenské zázemí v USA.\nCentrum města kombinuje koloniální architekturu s moderními budovami.\nMístní mexická kuchyně je považována za jednu z nejlepších v Texasu.\nKlimat je horký, ale atmosféra je přátelská a energická.\nSan Antonio je kulturním srdcem jižního Texasu.",
    "Houston": "Největší město Texasu a energetická metropole světa.\nHouston je domov NASA Johnson Space Center, odkud byly řízeny legendární kosmické mise.\nMěsto má rozmanitou kuchyni díky obrovské mezinárodní komunitě.\nZajímavostí je, že Houston nemá klasické územní plánování – město se rozrůstá velmi volně.\nDowntown nabízí muzea, divadla a moderní parky.\nKlimat je vlhký a horký, což dodává městu tropický nádech.\nHouston má silnou ekonomiku a rychle rostoucí populaci.\nJe to město příležitostí, vědy a multikulturní energie.",
    "Wichita Falls": "Severotexaské město na řece Wichita.\nWichita Falls je domovem letecké základny Sheppard AFB, která výrazně ovlivňuje místní ekonomiku.\nDowntown je menší, ale plný historických budov a lokálních podniků.\nZajímavostí je, že město má ikonický falešný „vodopád“, který byl uměle vytvořen.\nKrajina kolem je plochá, větrná a typicky texaská.\nMístní komunita je přátelská a soudržná.\nWichita Falls je klidnou zastávkou mezi Dallasem a Oklahomou.\nPůsobí jako pohodové, nenápadné město se silnými vojenskými kořeny.",
    "Galveston": "Pobřežní město na ostrově v Mexickém zálivu.\nGalveston má bohatou historii hurikánů, přístavu a viktoriánské architektury.\nPláže a promenády přitahují návštěvníky z celého Texasu.\nZajímavostí je, že roku 1900 zde došlo k nejsmrtelnější přírodní katastrofě v dějinách USA.\nMěsto má silnou lodní a turistickou tradici.\nDowntown Strand District nabízí historické domy, restaurace a galerie.\nKlima je vlhké a slané, s výrazným pobřežním charakterem.\nGalveston působí jako spojení historie, rekreace a mořského života.",
    "Odessa": "Pouštní město západního Texasu v oblasti Permian Basin.\nOdessa je úzce spojena s ropnou těžbou a drsným životem na ropných polích.\nMěsto má suché podnebí a široké silnice typické pro západní Texas.\nZajímavostí je, že zde stojí replika Stonehenge postavená u místní univerzity.\nOkolní krajina je plochá a působí nekonečně.\nOdessa má silnou sportovní tradici, zejména díky středoškolskému fotbalu.\nEkonomika města je svázaná s cenou ropy, což formuje jeho rytmus.\nOdessa nabízí autentický, syrový charakter texaského ropného světa.",
    "San Angelo": "Město u řeky Concho se silnou rančerskou a vojenskou historií.\nSan Angelo je známé krásným jezerem, parkem a historickým Fort Concho.\nArchitektura centra je směsicí starých západních budov a moderních prvků.\nZajímavostí je, že San Angelo má unikátně pestré ekosystémy díky řece.\nAtmosféra je klidná, slunečná a přátelská.\nMěsto je křižovatkou západního Texasu a univerzitního života.\nKulturní scéna zahrnuje galerie i tradiční rodeo akce.\nSan Angelo je pohodovým, teplým městem s hlubokými kořeny.",
    "Grand Marais": "Severní město Minnesoty ležící na břehu Lake Superior.\nMalý přístav a dřevěné domy vytvářejí útulnou atmosféru.\nOkolní boreální lesy a kopce jsou ideální pro pozorování polární záře.\nZajímavostí je, že Grand Marais bývá považováno za jedno z nejmalebnějších měst v USA.\nKomunita je kreativní a plná umělců, řemeslníků a outdoor nadšenců.\nPodnebí je drsné, ale krásné – zimy jsou sněhové a tiché.\nMěsto slouží jako vstupní brána k Boundary Waters Canoe Area Wilderness.\nGrand Marais působí malebně, klidně a inspirativně.",
    "Escanaba": "Město na horním poloostrově Michiganu, u břehů Lake Michigan.\nEscanaba má silnou rybářskou a papírenskou tradici.\nPřístav tvoří důležitou součást místního života.\nZajímavostí je, že oblast je známá výjimečně jasnou noční oblohou.\nPodnebí je chladné a zasněžené, typické pro severní státy.\nKomunita je přátelská a drží si tradiční hodnoty.\nKrajina je plná borovic, jezer a zimních sportovních aktivit.\nEscanaba je tichým, přírodou obklopeným městem Great Lakes regionu.",
    "Casper": "Energetické město Wyomingu ležící u North Platte River.\nCasper má dlouhou historii spojenou s ropným boomem a železnicí.\nOkolní hory a prérie vytvářejí dramatické scenérie.\nZajímavostí je, že Casper Mountain nabízí vynikající podmínky pro zimní sporty.\nCentrum města je menší, ale živé a plné lokálních podniků.\nKomunita zde silně podporuje outdoorové aktivity.\nVítr je zde téměř stálým společníkem – dodává městu divoký charakter.\nCasper představuje autentický život na rozmezí hor a plání.",
    "Monticello": "Malé město v jihovýchodním Utahu, obklopené červenými skalami a La Sal Mountains.\nMonticello je klidnou základnou pro výpravy do Canyonlands a Bears Ears.\nPříroda zde působí monumentálně a neporušeně.\nZajímavostí je, že město má neobvykle chladné noci díky vyšší nadmořské výšce.\nArchitektura je jednoduchá, přímá a typická pro horské komunity Utahu.\nMonticello je oblíbené pro turisty hledající tiché kempy a nádherné výhledy.\nAtmosféra je nenápadná, ale přátelská.\nMěsto je ideální základnou pro roadtripy po ikonické red rock krajině.",
    "Ely": "Klidné město ve vysoké poušti Nevady u legendární silnice US-50.\nEly má bohatou historii těžby a železniční dopravy, která je dodnes vidět v místním muzeu.\nNedaleko se nachází Great Basin National Park s nádhernými hvězdnými nocemi.\nZajímavostí je, že Ely patří mezi nejlepší místa pro pozorování noční oblohy v USA.\nOkolní krajina působí suše, tvrdě a nekonečně.\nMěsto pořádá malebný festival nástěnných maleb, který zdobí jeho historické ulice.\nKomunita je malá, ale soudržná a přátelská.\nEly je ideální zastávkou mezi pouští, horami a americkou silniční klasikou.",
    "Williston": "Ropné město Severní Dakoty v srdci oblasti Bakken.\nWilliston zažilo obrovský boom díky těžbě ropy, což radikálně změnilo jeho podobu.\nMěsto má silnou logistickou pozici na řece Missouri.\nZajímavostí je, že Williston patří mezi nejrychleji rostoucí města USA během ropných let.\nOkolní krajina tvoří otevřené pláně a široké horizonty.\nKomunita je směsicí dlouhodobých obyvatel a lidí, kteří přijeli za prací.\nZima je zde krutá, ale charakter regionu je nezdolný.\nWilliston představuje syrovou realitu moderní energetické éry.",
    "Jackson": "Hlavní město Mississippi, ležící na dálnici I-55.\nJackson má silné kořeny v soulové hudbě a hnutí za občanská práva.\nMěsto je plné historických památek, muzeí a jižanských tradic.\nZajímavostí je, že zde vzniklo mnoho ikonických soulových nahrávek.\nAtmosféra je pomalejší, teplejší a autenticky jižanská.\nKuchyně je výrazná – plná smažených specialit, koření a comfort food.\nKomunita je pestrá a kulturně propojená.\nJackson spojuje historii, hudbu a typickou jižanskou pohostinnost.",
    "New Orleans": "Město jazzu, Mardi Gras a kreolské kultury na řece Mississippi.\nNew Orleans je proslulé svou hudbou, gastronomií a historickou architekturou French Quarter.\nKaždá ulice zde vibruje rytmy, barvami a vůněmi místní kuchyně.\nZajímavostí je, že město je kolébkou jazzu a jedním z kulturně nejbohatších míst USA.\nNemesis města jsou hurikány, ale komunita je neuvěřitelně odolná.\nNoc zde nikdy nekončí – bary, trubači a světla žijí nonstop.\nPříchod k řece přináší nezaměnitelnou atmosféru delty.\nNew Orleans působí magicky, živě a absolutně jedinečně.",
    "Memphis": "Domov blues, rock’n’rollu a ikonické Beale Street.\nMemphis má hluboké hudební dědictví propojené s legendami jako Elvis Presley.\nGraceland je poutním místem fanoušků po celém světě.\nZajímavostí je, že město je jedním z největších logistických uzlů USA díky FedEx.\nMississippi River dodává městu široké a otevřené panorama.\nBBQ zde patří k nejlepším v celých Spojených státech.\nAtmosféra je drsná, horká a autenticky jižanská.\nMemphis je město, které zanechá stopu díky hudbě, rytmu a historii.",
    "Atlanta": "Hlavní uzel jihovýchodu a jedno z nejrychleji rostoucích měst USA.\nAtlanta má silný filmový průmysl a říká se jí „Hollywood of the South“.\nMěsto je centrem občanských práv díky odkazu Martina Luthera Kinga Jr.\nZajímavostí je, že Hartsfield–Jackson patří mezi nejrušnější letiště světa.\nKultura je zde moderní, energická a rozmanitá.\nCentrum je obklopeno zelenými čtvrtěmi a parky.\nAtlanta kombinuje jižanský šarm s globálním metropolitním charakterem.\nJe to město plné příležitostí, inovací a kulturní síly.",
    "Augusta": "Hlavní město Maine ležící na řece Kennebec.\nAugusta má klidnou, správní atmosféru typickou pro malé hlavní město.\nZajímavostí je, že město je jedno z nejstarších trvale osídlených míst v Nové Anglii.\nOkolí je plné hustých lesů, jezer a historických památek.\nPodnebí je chladné, s výraznými zimami i barevným podzimem.\nCentrum města je malé, ale útulné a historické.\nKomunita si drží tradiční hodnoty a životní rytmus.\nAugusta představuje tiché srdce severovýchodní Nové Anglie.",
    "Montgomery": "Hlavní město Alabamy na řece Alabama.\nMontgomery má zásadní roli v historii občanských práv a amerického Jihu.\nMěsto je domovem významných památníků, muzeí a historických tras.\nZajímavostí je, že zde začala slavná autobusová stávka vedená Rosou Parks.\nArchitektura zahrnuje jižanské domy, kapitolu a soudní budovy.\nPodnebí je teplé a vlhké, typické pro Deep South.\nAtmosféra je kulturní, historická a přívětivá.\nMontgomery spojuje tradice, historii a moderní jižanskou identitu.",
    "Charlotte": "Bankovní centrum Caroliny a jedno z nejrychleji rostoucích měst Jihu.\nCharlotte má moderní skyline a je domovem NASCAR Hall of Fame.\nMěsto je ekonomickou silou regionu s bohatým firemním zázemím.\nZajímavostí je, že Charlotte patří k největším finančním uzlům USA.\nAtmosféra je čistá, moderní a energická.\nZelené čtvrti a parky vytvářejí příjemné prostředí pro život.\nMěsto kombinuje jižanskou pohostinnost s rychlou expanzí.\nCharlotte je symbolem moderního Jihu.",
    "Raleigh": "Součást slavného Research Triangle spolu s Durhamem a Chapel Hill.\nRaleigh je město univerzit, technologií a vědeckého výzkumu.\nCentrum působí klidně, ale inovace zde mají obrovský dopad.\nZajímavostí je, že oblast má jednu z nejvzdělanějších populací v USA.\nRaleigh je zelené, tiché a velmi příjemné pro život.\nKultura je podpořená galeriemi, muzei a studentskou komunitou.\nMěsto je vyvážené a má stabilní růst.\nRaleigh je mozkem a srdcem vědeckého jihovýchodu.",
    "Cleveland": "Velkoměsto na břehu Erijského jezera s bohatou industriální historií.\nCleveland je domovem Rock & Roll Hall of Fame, což odráží jeho hudební kořeny.\nMěsto si prošlo vzestupy i pády, ale zažívá novou éru rozvoje.\nZajímavostí je, že Cleveland má jednu z nejlepších zdravotnických infrastruktur v USA.\nPobřeží a parky nabízejí příjemné rekreační možnosti.\nKultura zahrnuje divadla, sportovní týmy i silné lokální komunity.\nAtmosféra je pracovitá, upřímná a odolná.\nCleveland je město, které spojuje historii, tvrdou práci a moderní obnovu.",
    "Buffalo": "Město na severu státu New York, známé zimními sněhovými bouřemi a blízkostí Niagarských vodopádů.\nBuffalo má bohatou průmyslovou historii a krásné historické čtvrti.\nMěsto je domovem slavných Buffalo wings, které zde skutečně vznikly.\nZajímavostí je, že oblast byla kdysi elektrifikována jednou z prvních vodních elektráren světa.\nPodnebí je drsné, ale komunita je neuvěřitelně soudržná.\nPobřeží jezera Erie nabízí promenády, parky a přístavy.\nBuffalo zažívá moderní revitalizaci a růst v oblasti kultury a technologií.\nAtmosféra je hrdá, dělnická a plná lokální identity.",
    "Albany": "Hlavní město státu New York ležící u řeky Hudson.\nAlbany má dlouhou historii jako jedno z nejstarších měst USA.\nKapitola stojí na kopci a tvoří dominantní bod města.\nZajímavostí je, že Albany bylo první město s elektrickou tramvajovou sítí v zemi.\nKultura je směsí politických institucí, univerzit a historických budov.\nOkolní krajina nabízí krásné výlety do Adirondacks.\nMěsto působí klidně a stabilně s důrazem na administrativu.\nAlbany je přehledným a historickým centrem severního východu.",
    "New York": "Největší město USA a globální metropole, která nikdy nespí.\nNew York je mixem pěti čtvrtí plných ikonických míst – od Times Square po Central Park.\nMěsto je domovem světových financí, kultury a diverzity.\nZajímavostí je, že v NYC se mluví více než 800 jazyky.\nAtmosféra je rychlá, hlučná a inspirující.\nKaždá čtvrť má vlastní identitu: Manhattan je vertikální svět, Brooklyn kreativní a Queens multikulturní.\nSkyline je jedním z nejznámějších na planetě.\nNew York nabízí nekonečné možnosti, energii a příběhy.",
    "Philadelphia": "Historické město bratrské lásky a kolébka americké nezávislosti.\nPhiladelphia je domovem Liberty Bell, Independence Hall a bohaté kulturní scény.\nMěsto má dlouhou gastronomickou tradici – cheesesteaky jsou symbolem.\nZajímavostí je, že Philly má největší muralovou kolekci na světě.\nAtmosféra kombinuje tradiční ulice s moderním velkoměstem.\nSportovní komunita je vášnivá a intenzivní.\nCentrum je bohaté na muzea, parky i studentský život.\nPhiladelphia spojuje historii s dravou městskou energií.",
    "Baltimore": "Přístavní město Inner Harbor s výraznou kulturou a literární historií.\nBaltimore je domovem Edgara Allana Poea, jehož odkaz je dodnes patrný.\nMěsto je známé mořskými plody a modrými kraby z Chesapeake Bay.\nZajímavostí je, že Baltimore má více než 200 historických čtvrtí.\nAtmosféra je drsná, ale autentická a plná charakteru.\nInner Harbor kombinuje moderní muzeá a přístavní život.\nKultura zahrnuje hudbu, umění a lokální hrdost.\nBaltimore působí jako živé a jedinečné město východního pobřeží.",
    "Washington": "Hlavní město USA ležící na řece Potomac.\nWashington je domovem Bílého domu, Kapitolu a muzeí Smithsonian.\nMěsto má monumentální atmosféru díky širokým bulvárům a památníkům.\nZajímavostí je, že Washington nemá mrakodrapy – je to dáno zákonným omezením.\nKultura je politická, akademická a mezinárodní.\nČtvrti jako Georgetown či Capitol Hill mají osobitý historický ráz.\nAtmosféra je formální, ale zároveň velmi pestrá.\nWashington spojuje národní historii s moderním globálním centrem.",
    "Boston": "Historické jádro Nové Anglie s bohatou univerzitní a námořní tradicí.\nBoston je známý svými cihlovými uličkami, kampusy MIT a Harvardu i ikonickým přístavem.\nFreedom Trail spojuje mnoho zásadních míst americké historie.\nZajímavostí je, že Boston patří k nejchytřejším městům světa.\nSport je zde téměř náboženstvím – Red Sox, Celtics i Bruins.\nPodnebí přináší chladné zimy a krásná barevná podzimní období.\nAtmosféra kombinuje akademický svět s tradičními čtvrtěmi.\nBoston je elegantní, vzdělané a velmi karismatické město.",
    "Concord": "Hlavní město New Hampshire ležící u řeky Merrimack.\nMěsto je známé kompaktním centrem se státním Capitolem.\nOkolí tvoří kopcovitá krajina ideální pro výlety.\nZajímavostí je, že Concord byl významným centrem výroby kočárů v 19. století.\nKomunita je malá, ale aktivní a přátelská.\nPodnebí je chladné až drsné, typické pro Novou Anglii.\nAtmosféra je klidná a tradiční.\nConcord představuje tiché administrativní srdce severovýchodu.",
    "Richmond": "Historické hlavní město Virginie na břehu řeky James.\nRichmond je známý svou koloniální historií, street artem a craft scénou.\nMěsto má prudké říční peřeje přímo v centru, což je unikát mezi americkými městy.\nZajímavostí je, že Richmond byl hlavním městem Konfederace během občanské války.\nKultura je pestrá, moderní a rychle rostoucí.\nČtvrti jako Carytown jsou plné butiků, kaváren a umění.\nAtmosféra je mixem historie a současné kreativity.\nRichmond je překvapivě dynamické a energické město.",
    "Columbia": "Hlavní město Jižní Karolíny ležící u řeky Congaree.\nColumbia má silnou univerzitní atmosféru díky University of South Carolina.\nCentrum je živé, plné studentů, parků a historických čtvrtí.\nZajímavostí je, že město bylo během občanské války z velké části vypáleno.\nPodnebí je horké a vlhké, léto je velmi intenzivní.\nMístní komunita drží silné jižanské tradice.\nKultura kombinuje historii, sport a současné trendy.\nColumbia je dynamické jižanské město s přátelskou atmosférou.",
    "Tallahassee": "Hlavní město Floridy ležící na kopcích Panhandlu.\nTallahassee je známé státními institucemi, dubovými alejemi a univerzitním životem.\nFSU a další kampusy dodávají městu mladou a živou atmosféru.\nZajímavostí je, že Tallahassee není přímořské město – přesto působí jižansky tropicky.\nCentrum je kompaktní, historické a plné zeleně.\nSportovní život je zde intenzivní díky univerzitním týmům.\nPodnebí je teplé, vlhké a výrazně sezónní.\nTallahassee spojuje akademický svět, politiku a tradiční jižanskou kulturu.",
    "Orlando": "Centrální město Floridy známé svými obřími zábavními resorty a kongresovým centrem.\nOrlando je světovým centrem theme parků – od Disney Worldu po Universal Studios.\nMěsto má stovky jezer, která vytvářejí krásnou krajinnou mozaiku.\nZajímavostí je, že Orlando patří mezi nejnavštěvovanější destinace světa.\nKultura je ovlivněna turismem, mezinárodní komunitou a moderním rozvojem.\nPodnebí je horké a vlhké, s častými odpoledními bouřkami.\nDowntown nabízí sportovní arény, bary a živou noční scénu.\nOrlando kombinuje tropický životní styl s neustálou zábavou a energií.",
    "Nashville": "Hudební metropole Tennessee a domov country scény.\nNashville je známé svými honky-tonk bary, Grand Ole Opry a skladatelskými studii.\nMěsto přitahuje hudebníky z celého světa.\nZajímavostí je, že přezdívka „Music City“ vznikla díky univerzitnímu sboru v 19. století.\nEkonomika města rychle roste díky tech a zdravotnickému sektoru.\nAtmosféra je přátelská, živá a autenticky jižanská.\nNoční život je plný hudby a energie.\nNashville spojuje tradici, moderní vývoj a silnou kulturní identitu.",
    "Springfield": "Hlavní město Illinois, úzce spojené s životem Abrahama Lincolna.\nMěsto je plné muzeí, památníků a historických budov.\nDowntown působí klidně, úředně a tradičně.\nZajímavostí je, že mnoho míst zdejšího města je zachováno přesně tak, jak je Lincoln znal.\nPodnebí přináší chladné zimy a teplá léta.\nAtmosféra je typická pro středozápad – přátelská a poklidná.\nOkolní prérie vytvářejí otevřenou scenérii.\nSpringfield je místem americké historie a občanských hodnot.",
    "Jefferson City": "Kapitál Missouri ležící na řece Missouri.\nDominantou města je krásný Capitol s výhledem na řeku.\nMěsto má kompaktní historické centrum obklopené zelenými kopci.\nZajímavostí je, že Jefferson City je jedno z nejmalebnějších hlavních měst USA.\nKomunita je klidná a přátelská.\nOkolní příroda podporuje turistiku, cyklistiku i výlety po řece.\nKultura je zde spojená se státní správou a tradičními hodnotami.\nJefferson City je harmonickou kombinací historie, politiky a krajiny.",
    "Topeka": "Hlavní město Kansasu ležící u řeky Kansas.\nTopeka má významné místo v historii občanských práv díky případu Brown v. Board of Education.\nMěsto působí klidně, administrativně a středozápadně.\nZajímavostí je, že Topeka byla kdysi velkým železničním uzlem regionu.\nPodnebí je suché a větrné, typické pro Kansas.\nKultura je propojena s univerzitami, muzei a místními podniky.\nAtmosféra je přívětivá a nenápadná.\nTopeka je bránou do prérijních oblastí i centrálního Kansasu.",
    "Lincoln": "Hlavní město Nebrasky s charakteristickým mrakodrapovým Capitolem.\nLincoln je univerzitní město s živou studentskou atmosférou.\nCentrum kombinuje historické budovy s moderními podniky.\nZajímavostí je, že Capitol v Lincolnu je jednou z nejvýraznějších státních budov v USA.\nKultura je silně zaměřena na sport, zejména univerzitní fotbal.\nOkolní krajina je tvořena otevřenými poli a mírným prérijním reliéfem.\nAtmosféra je pohodová a přátelská.\nLincoln spojuje akademický svět, tradice a rurální charakter Nebrasky.",
    "Louisville": "Město na řece Ohio proslavené Kentucky Derby.\nLouisville má silnou tradici bourbonu, baseballu a jižanské kultury.\nDowntown kombinuje historické budovy s moderními čtvrtěmi.\nZajímavostí je, že město je rodištěm Muhammada Aliho.\nKulinářská scéna je pestrá a ovlivněná jihozápadními i středozápadními chutěmi.\nAtmosféra je nenucená, kulturní a přívětivá.\nLouisville má překvapivě rozsáhlý parkový systém.\nMěsto je živým mixem sportu, historie a gastronomie.",
    "Omaha": "Logistické a firemní centrum Nebrasky ležící u řeky Missouri.\nOmaha má dlouhou historii jako město stockyards a železnice.\nModerní downtown se rychle rozvíjí díky firmám a startupům.\nZajímavostí je, že zde sídlí Warren Buffett, jeden z nejznámějších investorů světa.\nOmaha má výbornou zoo, považovanou za jednu z nejlepších na planetě.\nKomunita je pracovitá a otevřená.\nMěsto spojuje industriální kořeny s moderní ekonomikou.\nOmaha je stabilní a pohostinná metropole středozápadu.",
    "Wichita": "Letecké město Kansasu se silnou průmyslovou historií.\nWichita je domovem mnoha výrobců letadel, což mu přineslo přezdívku „Air Capital of the World“.\nDowntown prošel velkou obnovou a je plný muzeí a restaurací.\nZajímavostí je, že zde vznikl první Pizza Hut na světě.\nKultura zahrnuje rodeo, letecké festivaly a univerzitní život.\nOkolí nabízí široké prérijní horizonty.\nAtmosféra je pracovitá, upřímná a typicky kansaská.\nWichita je klíčovým dopravním a průmyslovým uzlem regionu.",
    "Tulsa": "Art Deco perla Oklahomy s bohatou ropnou historií.\nCentrum města je plné nádherných budov z éry ropné prosperity.\nTulsa má živou hudební scénu, bluesové kořeny a moderní rozvoj.\nZajímavostí je, že město vybudovalo světově proslulý park Gathering Place.\nRoute 66 dodává ulicím nostalgickou retro atmosféru.\nPromenády a mosty kolem Arkansas River oživují centrum.\nKomunita je hrdá a kulturně výrazná.\nTulsa spojuje historii, eleganci a současné trendy.",
    "Baton Rouge": "Hlavní město Louisiany ležící na řece Mississippi.\nBaton Rouge kombinuje kreolské tradice, historickou architekturu a moderní petrochemický průmysl.\nMěsto je domovem LSU, jehož sportovní týmy vytvářejí jedinečnou atmosféru.\nZajímavostí je, že místní Capitol je nejvyšší státní Kapitol v celých USA.\nPobřeží řeky nabízí muzea, historické lodě a kulturní akce.\nKuchyně je plná cajun a kreolských chutí s bohatými kořeněnými pokrmy.\nPodnebí je horké, vlhké a velmi typické pro americký Jih.\nBaton Rouge působí jako energické, hrdé a kulturně bohaté město.",
    "Birmingham": "Průmyslové srdce Alabamy a hlavní centrum ocelářství amerického Jihu.\nBirmingham hrál zásadní roli během hnutí za občanská práva v 60. letech.\nDnes je město moderním centrem technologií, medicíny a vzdělávání.\nZajímavostí je, že zde stojí největší litinová socha světa – Vulcan.\nHistorické čtvrti se mísí s novými restauracemi, pivovary a kulturní scénou.\nPodnebí je teplé a vlhké, ale okolní kopce vytvářejí krásné vyhlídky.\nMěsto má silné hudební kořeny v blues a gospel tradici.\nBirmingham spojuje industriální minulost s moderní jižanskou identitou.",
    "Jacksonville": "Největší město Floridy podle rozlohy, ležící u řeky St. Johns.\nJacksonville kombinuje městský život, pláže a rozsáhlé zelené plochy.\nMěsto má velkou námořní historii a vojenskou přítomnost.\nZajímavostí je, že Jacksonville má jednu z nejdelších městských pláží v USA.\nKultura je směsicí jižanských tradic, moderních trendů a surfové atmosféry.\nCentrum se rychle rozvíjí díky novým podnikům a technologické scéně.\nPodnebí je tropické, s horkými léty a mírnými zimami.\nJacksonville je aktivní, rozlehlé a příjemně pobřežní město.",
    "Tampa": "Pobřežní metropole Floridy v oblasti Tampa Bay.\nMěsto je známé svým přístavem, sportovními týmy a festivalem Gasparilla.\nTampa má silný kubánský vliv, zejména ve čtvrti Ybor City.\nZajímavostí je, že zde vznikl původní kubánský sendvič – Cuban sandwich.\nModerní downtown je plný promenád, muzeí a výhledů na záliv.\nPodnebí je tropické, s teplými zimami a vlhkými léty.\nMístní kultura spojuje pláže, historii a zábavu.\nTampa je dynamická, slunečná a přátelská metropole západní Floridy.",
    "Miami": "Tropická metropole jihu Floridy s ikonickým Art Deco a latinskoamerickým vlivem.\nMiami je známé plážemi, nočním životem a živou kulturní scénou.\nMěsto je branou do Karibiku a Latinské Ameriky.\nZajímavostí je, že Miami má jednu z největších kubánských komunit na světě.\nCentrum se rychle rozvíjí a stává se technologickým a finančním uzlem.\nPodnebí je horké, vlhké a velmi slunečné.\nPobřeží je plné promenád, hotelů a ikonických palem.\nMiami je energické, barevné a jedinečně kosmopolitní.",
    "Pittsburgh": "Město mostů na soutoku tří řek s hlubokou ocelářskou historií.\nPittsburgh se proměnil z industriálního centra v moderní hub technologií a vzdělávání.\nMěsto je obklopeno zelenými kopci, což vytváří jedinečné panoramatické výhledy.\nZajímavostí je, že Pittsburgh má více mostů než Benátky.\nKultura zahrnuje divadla, muzea a slavné sportovní týmy.\nPodnebí je proměnlivé, ale dodává městu charakter.\nKolejová doprava a staré železnice připomínají jeho industriální minulost.\nPittsburgh je pracovitý, stylový a překvapivě inovativní.",
    "Chicago": "Metropole u jezera Michigan a jedno z největších měst USA.\nChicago je známé svým impozantním skyline, deep-dish pizzou a bohatou architektonickou historií.\nMěsto má silné kořeny v blues, jazzu a literatuře.\nZajímavostí je, že Chicago bylo domovem prvního mrakodrapu na světě.\nLake Shore Drive a nábřežní parky vytvářejí krásné výhledy.\nPodnebí je větrné a zimy jsou zde velmi drsné.\nMěsto má rozmanitou komunitu a silnou uměleckou scénu.\nChicago je živé, kulturně bohaté a architektonicky ikonické.",
    "Detroit": "Motor City a historické centrum amerického automobilového průmyslu.\nDetroit byl domovem značek Ford, GM i Chrysler, které změnily svět dopravy.\nMěsto má hlubokou hudební tradici díky Motown Records.\nZajímavostí je, že některé staré továrny se mění v galerie, studia a nové čtvrti.\nDetroit zažívá velkou renesanci díky startupům a umělecké komunitě.\nPodnebí je kontinentální, s výraznými zimami.\nCentrum nabízí zrekonstruované parky, arény a historické budovy.\nDetroit spojuje industriální minulost s moderní energií.",
    "Kansas City": "Město barbecue, jazzu a fontán rozdělené hranicí mezi Missouri a Kansas.\nKansas City má silnou hudební tradici a historické jazzové kluby.\nBBQ je zde považováno za umění – město je gastronomickým centrem regionu.\nZajímavostí je, že KC má více fontán než většina světových metropolí.\nDowntown prošel velkou revitalizací a působí moderně a přívětivě.\nSport hraje velkou roli, od Chiefs po baseballové Royals.\nPodnebí je střídavé, s horkými léty a chladnými zimami.\nKansas City kombinuje uvolněnou atmosféru s kulturní hloubkou.",
    "St. Louis": "Město na Mississippi s ikonickým obloukem Gateway Arch.\nSt. Louis má bohatou historii průkopníků, obchodu a amerického expanzního období.\nMěsto má silnou sportovní identitu a tradiční čtvrti plné cihlových domů.\nZajímavostí je, že právě zde vzniklo pivo Budweiser.\nThe Hill je známé svou italskou gastronomií a komunitou.\nPodnebí je vlhké, s výraznými letními teplotami.\nMěsto je plné muzeí, mostů a historických parků.\nSt. Louis spojuje průmyslové kořeny s moderním městským životem.",
    "Indianapolis": "Hlavní město Indiany a domov slavného závodu Indy 500.\nIndianapolis má kompaktní centrum s pěkným kanálem, muzei a sportovními arénami.\nMěsto je významným logistickým uzlem Spojených států.\nZajímavostí je, že Indy 500 je největší jednodenní sportovní událost na světě.\nKultura zahrnuje divadla, festivaly a silnou sportovní tradici.\nPodnebí je typicky středomořské s chladnými zimami.\nAtmosféra je přátelská a pracovitá.\nIndianapolis spojuje moderní infrastrukturu s dlouhou závodní historií.",
    "Cincinnati": "Historické město na řece Ohio známé svými mosty, kopci a německým dědictvím.\nCincinnati má krásné historické čtvrti a jeden z nejstarších zoo parků v USA.\nMěsto je domovem ikonických architektonických staveb a silných sportovních klubů.\nZajímavostí je, že Cincinnati bylo kdysi největším městem na americkém Západě.\nLokální kuchyně je proslulá svou netradiční Cincinnati chili.\nKultura je směsicí středozápadu a jižanských vlivů.\nCentrum je plné kaváren, galerií a moderních podniků.\nCincinnati je elegantní, přívětivé a kulturně pestré město.",
    "Columbus": "Hlavní město Ohia a domov obří univerzity Ohio State.\nColumbus je rychle rostoucí město s moderním technologickým a kreativním sektorem.\nKultura je mladá, otevřená a velmi inovativní.\nZajímavostí je, že Columbus má jednu z největších komunit módního průmyslu v USA.\nČtvrti jako Short North jsou plné galerií a barů.\nPodnebí je mírné se čtyřmi výraznými ročními obdobími.\nMěsto je rozmanité a přátelské.\nColumbus spojuje akademický svět, obchod a moderní městský život.",
    "Wichita": "Letecké město Kansasu a dlouholetá „Air Capital of the World“.\nWichita je domovem mnoha výrobců letadel a leteckých muzeí.\nMěsto má silnou průmyslovou historii a pracovitý charakter.\nZajímavostí je, že zde vznikl první Pizza Hut na světě.\nDowntown prošel obnovou a nabízí galerie, bary a nové parky.\nKultura je směsicí rodea, technologií a středozápadních tradic.\nPodnebí je suché a větrné, typické pro Kansas.\nWichita je dynamické, otevřené a příjemně živé město střední Ameriky.",

}

POPULATION_MAP = {
    "Seattle": 733000,
    "Olympia": 56000,
    "Portland": 653000,
    "Astoria": 10000,
    "Salem": 179000,
    "Spokane": 229000,
    "Boise": 236000,
    "Helena": 32000,
    "Bismarck": 74000,
    "San Francisco": 808000,
    "Oakland": 433000,
    "San Jose": 971000,
    "Sacramento": 528000,
    "Fresno": 545000,
    "Bakersfield": 409000,
    "Los Angeles": 3820000,
    "San Diego": 1389000,
    "Eureka": 27000,
    "Las Vegas": 656000,
    "Phoenix": 1644000,
    "Tucson": 543000,
    "Monticello": 3000,
    "Ely": 4000,
    "Salt Lake City": 201000,
    "Denver": 711000,
    "Colorado Springs": 489000,
    "Santa Fe": 89000,
    "Casper": 59000,
    "Albuquerque": 565000,
    "Cheyenne": 65000,
    "Pierre": 14000,
    "Sheridan": 19000,
    "Minneapolis": 425000,
    "Milwaukee": 563000,
    "Escanaba": 12000,
    "Chicago": 2665000,
    "Grand Marais": 1000,
    "Williston": 28000,
    "Detroit": 620000,
    "Kansas City": 509000,
    "Jefferson City": 42000,
    "St. Louis": 301000,
    "Springfield": 113000,
    "Indianapolis": 880000,
    "Cincinnati": 309000,
    "Louisville": 626000,
    "Lincoln": 293000,
    "Columbus": 906000,
    "Omaha": 487000,
    "Topeka": 125000,
    "Wichita": 398000,
    "Oklahoma City": 701000,
    "Tulsa": 412000,
    "Little Rock": 201000,
    "El Paso": 678000,
    "Amarillo": 201000,
    "Odessa": 115000,
    "Wichita Falls": 103000,
    "Dallas": 1309000,
    "Austin": 978000,
    "San Angelo": 101000,
    "San Antonio": 1472000,
    "Houston": 2302000,
    "Galveston": 53000,
    "Jackson": 150000,
    "New Orleans": 377000,
    "Baton Rouge": 221000,
    "Memphis": 633000,
    "Nashville": 690000,
    "Atlanta": 510000,
    "Augusta": 19000,
    "Montgomery": 199000,
    "Birmingham": 197000,
    "Charlotte": 897000,
    "Raleigh": 474000,
    "Jacksonville": 971000,
    "Tallahassee": 201000,
    "Orlando": 312000,
    "Tampa": 399000,
    "Miami": 449000,
    "Pittsburgh": 303000,
    "Cleveland": 362000,
    "Buffalo": 276000,
    "Albany": 101000,
    "New York": 8336000,
    "Philadelphia": 1567000,
    "Baltimore": 569000,
    "Washington": 671000,
    "Boston": 654000,
    "Concord": 44000,
    "Richmond": 228000,
    "Columbia": 137000,
}

CITIES = [
    {
        "name": "Seattle",
        "region": "pacific_northwest",
        "importance": 1,
        "lat": 46.9062,
        "lon": -119.1321,
        "px": 72.38,
        "py": 69.5,
        "grid_x": 8,
        "grid_y": 9,
    },
    {
        "name": "Olympia",
        "region": "pacific_northwest",
        "importance": 2,
        "lat": 47.0379,
        "lon": -122.9007,
        "px": 68.0,
        "py": 82.0,
        "grid_x": 8,
        "grid_y": 11,
    },
    {
        "name": "Portland",
        "region": "pacific_northwest",
        "importance": 3,
        "lat": 45.2051,
        "lon": -119.725,
        "px": 61.61,
        "py": 109.61,
        "grid_x": 7,
        "grid_y": 14,
    },
    {
        "name": "Astoria",
        "region": "pacific_northwest",
        "importance": 3,
        "lat": 46.1879,
        "lon": -123.8313,
        "px": 49.0,
        "py": 95.0,
        "grid_x": 5,
        "grid_y": 12,
    },
    {
        "name": "Salem",
        "region": "pacific_northwest",
        "importance": 2,
        "lat": 44.9429,
        "lon": -123.0351,
        "px": 60.0,
        "py": 122.0,
        "grid_x": 8,
        "grid_y": 17,
    },
    {
        "name": "Spokane",
        "region": "pacific_northwest",
        "importance": 3,
        "lat": 46.0588,
        "lon": -115.426,
        "px": 134.73,
        "py": 89.48,
        "grid_x": 17,
        "grid_y": 11,
    },
    {
        "name": "Boise",
        "region": "pacific_northwest",
        "importance": 2,
        "lat": 42.115,
        "lon": -115.1023,
        "px": 140.62,
        "py": 182.46,
        "grid_x": 18,
        "grid_y": 23,
    },
    {
        "name": "Helena",
        "region": "pacific_northwest",
        "importance": 2,
        "lat": 44.9884,
        "lon": -111.0245,
        "px": 214.72,
        "py": 114.72,
        "grid_x": 27,
        "grid_y": 14,
    },
    {
        "name": "Bismarck",
        "region": "pacific_northwest",
        "importance": 2,
        "lat": 44.2083,
        "lon": -100.7837,
        "px": 400.82,
        "py": 133.11,
        "grid_x": 50,
        "grid_y": 17,
    },
    {
        "name": "San Francisco",
        "region": "pacific_southwest",
        "importance": 2,
        "lat": 37.7749,
        "lon": -121.4194,
        "px": 25.82,
        "py": 284.78,
        "grid_x": 3,
        "grid_y": 36,
    },
    {
        "name": "Oakland",
        "region": "pacific_southwest",
        "importance": 3,
        "lat": 37.9044,
        "lon": -121.2711,
        "px": 28.51,
        "py": 281.73,
        "grid_x": 4,
        "grid_y": 35,
    },
    {
        "name": "San Jose",
        "region": "pacific_southwest",
        "importance": 3,
        "lat": 37.3382,
        "lon": -120.8863,
        "px": 35.51,
        "py": 295.08,
        "grid_x": 4,
        "grid_y": 37,
    },
    {
        "name": "Sacramento",
        "region": "pacific_southwest",
        "importance": 2,
        "lat": 38.5816,
        "lon": -120.5944,
        "px": 40.81,
        "py": 265.76,
        "grid_x": 5,
        "grid_y": 33,
    },
    {
        "name": "Fresno",
        "region": "pacific_southwest",
        "importance": 3,
        "lat": 36.7378,
        "lon": -119.7871,
        "px": 55.48,
        "py": 309.23,
        "grid_x": 7,
        "grid_y": 39,
    },
    {
        "name": "Bakersfield",
        "region": "pacific_southwest",
        "importance": 3,
        "lat": 35.3733,
        "lon": -119.0187,
        "px": 70.44,
        "py": 336.4,
        "grid_x": 9,
        "grid_y": 43,
    },
    {
        "name": "Los Angeles",
        "region": "pacific_southwest",
        "importance": 1,
        "lat": 34.0522,
        "lon": -118.2437,
        "px": 78.53,
        "py": 366.55,
        "grid_x": 10,
        "grid_y": 47,
    },
    {
        "name": "San Diego",
        "region": "pacific_southwest",
        "importance": 2,
        "lat": 32.7157,
        "lon": -117.1611,
        "px": 102.2,
        "py": 395.0,
        "grid_x": 13,
        "grid_y": 49,
    },
    {
        "name": "Eureka",
        "region": "pacific_southwest",
        "importance": 3,
        "lat": 41.0021,
        "lon": -122.1637,
        "px": 12.29,
        "py": 208.7,
        "grid_x": 2,
        "grid_y": 26,
    },
    {
        "name": "Las Vegas",
        "region": "mountain",
        "importance": 3,
        "lat": 36.1699,
        "lon": -115.1398,
        "px": 139.93,
        "py": 332.62,
        "grid_x": 17,
        "grid_y": 40,
    },
    {
        "name": "Phoenix",
        "region": "mountain",
        "importance": 2,
        "lat": 32.8484,
        "lon": -112.074,
        "px": 195.65,
        "py": 400.93,
        "grid_x": 24,
        "grid_y": 50,
    },
    {
        "name": "Tucson",
        "region": "mountain",
        "importance": 3,
        "lat": 31.8026,
        "lon": -110.9747,
        "px": 215.63,
        "py": 425.58,
        "grid_x": 27,
        "grid_y": 53,
    },
    {
        "name": "Monticello",
        "region": "mountain",
        "importance": 3,
        "lat": 37.8714,
        "lon": -109.3426,
        "px": 240.0,
        "py": 330.0,
        "grid_x": 30,
        "grid_y": 41,
    },
    {
        "name": "Ely",
        "region": "mountain",
        "importance": 3,
        "lat": 39.247,
        "lon": -114.888,
        "px": 148.0,
        "py": 280.0,
        "grid_x": 19,
        "grid_y": 39,
    },
    {
        "name": "Salt Lake City",
        "region": "mountain",
        "importance": 1,
        "lat": 39.7608,
        "lon": -111.891,
        "px": 209.97,
        "py": 244.96,
        "grid_x": 25,
        "grid_y": 30,
    },
    {
        "name": "Denver",
        "region": "mountain",
        "importance": 1,
        "lat": 37.5392,
        "lon": -104.9903,
        "px": 324.38,
        "py": 290.34,
        "grid_x": 41,
        "grid_y": 36,
    },
    {
        "name": "Colorado Springs",
        "region": "mountain",
        "importance": 3,
        "lat": 36.8339,
        "lon": -104.8214,
        "px": 327.45,
        "py": 306.96,
        "grid_x": 41,
        "grid_y": 38,
    },
    {
        "name": "Santa Fe",
        "region": "mountain",
        "importance": 3,
        "lat": 34.787,
        "lon": -105.9378,
        "px": 307.16,
        "py": 355.22,
        "grid_x": 38,
        "grid_y": 44,
    },
    {
        "name": "Casper",
        "region": "mountain",
        "importance": 3,
        "lat": 42.8501,
        "lon": -106.3252,
        "px": 310.0,
        "py": 210.0,
        "grid_x": 39,
        "grid_y": 26,
    },
    {
        "name": "Albuquerque",
        "region": "mountain",
        "importance": 3,
        "lat": 33.8844,
        "lon": -106.6504,
        "px": 294.21,
        "py": 376.5,
        "grid_x": 37,
        "grid_y": 47,
    },
    {
        "name": "Cheyenne",
        "region": "mountain",
        "importance": 2,
        "lat": 39.1,
        "lon": -104.1202,
        "px": 340.19,
        "py": 253.54,
        "grid_x": 43,
        "grid_y": 32,
    },
    {
        "name": "Pierre",
        "region": "mountain",
        "importance": 2,
        "lat": 41.9683,
        "lon": -100.35,
        "px": 408.7,
        "py": 185.92,
        "grid_x": 51,
        "grid_y": 23,
    },
    {
        "name": "Sheridan",
        "region": "mountain",
        "importance": 3,
        "lat": 42.5972,
        "lon": -106.9562,
        "px": 288.65,
        "py": 171.09,
        "grid_x": 36,
        "grid_y": 21,
    },
    {
        "name": "Minneapolis",
        "region": "midwest_north",
        "importance": 3,
        "lat": 42.9778,
        "lon": -93.265,
        "px": 537.46,
        "py": 162.12,
        "grid_x": 67,
        "grid_y": 20,
    },
    {
        "name": "Milwaukee",
        "region": "midwest_north",
        "importance": 3,
        "lat": 41.2389,
        "lon": -89.7065,
        "px": 602.12,
        "py": 203.11,
        "grid_x": 75,
        "grid_y": 25,
    },
    {
        "name": "Escanaba",
        "region": "midwest_north",
        "importance": 3,
        "lat": 45.745,
        "lon": -87.0646,
        "px": 660.0,
        "py": 190.0,
        "grid_x": 83,
        "grid_y": 24,
    },
    {
        "name": "Chicago",
        "region": "midwest_north",
        "importance": 1,
        "lat": 39.4781,
        "lon": -89.1298,
        "px": 612.6,
        "py": 244.63,
        "grid_x": 77,
        "grid_y": 31,
    },
    {
        "name": "Grand Marais",
        "region": "midwest_north",
        "importance": 3,
        "lat": 47.7504,
        "lon": -90.3345,
        "px": 563.0,
        "py": 125.0,
        "grid_x": 72,
        "grid_y": 17,
    },
    {
        "name": "Williston",
        "region": "mountain",
        "importance": 3,
        "lat": 48.1469,
        "lon": -103.618,
        "px": 350.0,
        "py": 112.0,
        "grid_x": 44,
        "grid_y": 18,
    },
    {
        "name": "Detroit",
        "region": "midwest_north",
        "importance": 2,
        "lat": 40.5314,
        "lon": -84.5458,
        "px": 695.91,
        "py": 219.79,
        "grid_x": 87,
        "grid_y": 27,
    },
    {
        "name": "Kansas City",
        "region": "midwest_central",
        "importance": 3,
        "lat": 37.0997,
        "lon": -94.5786,
        "px": 513.59,
        "py": 305.7,
        "grid_x": 64,
        "grid_y": 38,
    },
    {
        "name": "Jefferson City",
        "region": "midwest_central",
        "importance": 2,
        "lat": 38.5767,
        "lon": -92.1735,
        "px": 552.0,
        "py": 320.0,
        "grid_x": 67,
        "grid_y": 40,
    },
    {
        "name": "St. Louis",
        "region": "midwest_central",
        "importance": 2,
        "lat": 36.627,
        "lon": -90.1994,
        "px": 593.17,
        "py": 314.84,
        "grid_x": 74,
        "grid_y": 39,
    },
    {
        "name": "Springfield",
        "region": "midwest_central",
        "importance": 3,
        "lat": 39.7817,
        "lon": -89.6501,
        "px": 610.0,
        "py": 298.0,
        "grid_x": 76,
        "grid_y": 41,
    },
    {
        "name": "Indianapolis",
        "region": "midwest_central",
        "importance": 2,
        "lat": 37.9684,
        "lon": -86.6581,
        "px": 657.52,
        "py": 280.22,
        "grid_x": 82,
        "grid_y": 35,
    },
    {
        "name": "Cincinnati",
        "region": "midwest_central",
        "importance": 3,
        "lat": 37.3031,
        "lon": -84.912,
        "px": 689.25,
        "py": 295.9,
        "grid_x": 86,
        "grid_y": 37,
    },
    {
        "name": "Louisville",
        "region": "midwest_central",
        "importance": 2,
        "lat": 38.2527,
        "lon": -85.7585,
        "px": 674.0,
        "py": 314.0,
        "grid_x": 84,
        "grid_y": 39,
    },
    {
        "name": "Lincoln",
        "region": "midwest_central",
        "importance": 2,
        "lat": 40.8136,
        "lon": -96.7026,
        "px": 470.0,
        "py": 282.0,
        "grid_x": 59,
        "grid_y": 36,
    },
    {
        "name": "Columbus",
        "region": "midwest_central",
        "importance": 2,
        "lat": 38.3612,
        "lon": -83.2988,
        "px": 718.57,
        "py": 270.96,
        "grid_x": 90,
        "grid_y": 34,
    },
    {
        "name": "Omaha",
        "region": "midwest_central",
        "importance": 3,
        "lat": 39.2565,
        "lon": -95.9345,
        "px": 488.95,
        "py": 249.85,
        "grid_x": 61,
        "grid_y": 31,
    },
    {
        "name": "Topeka",
        "region": "midwest_central",
        "importance": 3,
        "lat": 39.0483,
        "lon": -95.678,
        "px": 495.0,
        "py": 315.0,
        "grid_x": 62,
        "grid_y": 40,
    },
    {
        "name": "Wichita",
        "region": "midwest_central",
        "importance": 3,
        "lat": 35.6872,
        "lon": -97.3301,
        "px": 463.58,
        "py": 334,
        "grid_x": 58,
        "grid_y": 42,
    },
    {
        "name": "Oklahoma City",
        "region": "midwest_central",
        "importance": 2,
        "lat": 35.4676,
        "lon": -97.5164,
        "px": 470.0,
        "py": 380.0,
        "grid_x": 59,
        "grid_y": 48,
    },
    {
        "name": "Tulsa",
        "region": "midwest_central",
        "importance": 3,
        "lat": 34.15398,
        "lon": -95.99277,
        "px": 487.89,
        "py": 370.15,
        "grid_x": 61,
        "grid_y": 46,
    },
    {
        "name": "Little Rock",
        "region": "midwest_central",
        "importance": 3,
        "lat": 32.7465,
        "lon": -92.2896,
        "px": 555.18,
        "py": 403.33,
        "grid_x": 69,
        "grid_y": 50,
    },
    {
        "name": "El Paso",
        "region": "southwest",
        "importance": 2,
        "lat": 31.3619,
        "lon": -107.185,
        "px": 284.49,
        "py": 435.97,
        "grid_x": 36,
        "grid_y": 54,
    },
    {
        "name": "Amarillo",
        "region": "southwest",
        "importance": 3,
        "lat": 32.7555,
        "lon": -100.3308,
        "px": 388.05,
        "py": 393.12,
        "grid_x": 51,
        "grid_y": 50,
    },
    {
        "name": "Odessa",
        "region": "southwest",
        "importance": 3,
        "lat": 31.8457,
        "lon": -102.3676,
        "px": 350.0,
        "py": 445.0,
        "grid_x": 44,
        "grid_y": 56,
    },
    {
        "name": "Wichita Falls",
        "region": "south_central",
        "importance": 3,
        "lat": 33.9137,
        "lon": -98.4934,
        "px": 445.0,
        "py": 402.0,
        "grid_x": 57,
        "grid_y": 49,
    },
    {
        "name": "Dallas",
        "region": "south_central",
        "importance": 1,
        "lat": 31.4767,
        "lon": -96.797,
        "px": 473.27,
        "py": 433.26,
        "grid_x": 59,
        "grid_y": 54,
    },
    {
        "name": "Austin",
        "region": "south_central",
        "importance": 2,
        "lat": 29.4672,
        "lon": -98.7431,
        "px": 437.91,
        "py": 480.64,
        "grid_x": 55,
        "grid_y": 60,
    },
    {
        "name": "San Angelo",
        "region": "south_central",
        "importance": 3,
        "lat": 31.4424,
        "lon": -100.4503,
        "px": 395.0,
        "py": 470.0,
        "grid_x": 49,
        "grid_y": 59,
    },
    {
        "name": "San Antonio",
        "region": "south_central",
        "importance": 3,
        "lat": 28.5241,
        "lon": -100.4936,
        "px": 406.09,
        "py": 502.87,
        "grid_x": 51,
        "grid_y": 63,
    },
    {
        "name": "Houston",
        "region": "south_central",
        "importance": 2,
        "lat": 29.1604,
        "lon": -96.3698,
        "px": 475.03,
        "py": 487.87,
        "grid_x": 60,
        "grid_y": 61,
    },
    {
        "name": "Galveston",
        "region": "south_central",
        "importance": 3,
        "lat": 29.3013,
        "lon": -94.7977,
        "px": 485.0,
        "py": 504.0,
        "grid_x": 63,
        "grid_y": 64,
    },
    {
        "name": "Jackson",
        "region": "south_central",
        "importance": 2,
        "lat": 31.0288,
        "lon": -90.1848,
        "px": 593.43,
        "py": 443.82,
        "grid_x": 74,
        "grid_y": 55,
    },
    {
        "name": "New Orleans",
        "region": "south_central",
        "importance": 3,
        "lat": 29.2511,
        "lon": -90.6715,
        "px": 584.59,
        "py": 485.73,
        "grid_x": 73,
        "grid_y": 61,
    },
    {
        "name": "Baton Rouge",
        "region": "south_central",
        "importance": 2,
        "lat": 30.4515,
        "lon": -91.1871,
        "px": 565.0,
        "py": 470.0,
        "grid_x": 71,
        "grid_y": 59,
    },
    {
        "name": "Memphis",
        "region": "south_central",
        "importance": 3,
        "lat": 33.1495,
        "lon": -90.049,
        "px": 595.9,
        "py": 393.83,
        "grid_x": 74,
        "grid_y": 49,
    },
    {
        "name": "Nashville",
        "region": "southeast",
        "importance": 2,
        "lat": 36.1627,
        "lon": -86.7816,
        "px": 648.0,
        "py": 360.0,
        "grid_x": 81,
        "grid_y": 45,
    },
    {
        "name": "Atlanta",
        "region": "southeast",
        "importance": 1,
        "lat": 32.749,
        "lon": -84.388,
        "px": 698.78,
        "py": 403.27,
        "grid_x": 87,
        "grid_y": 50,
    },
    {
        "name": "Augusta",
        "region": "northeast",
        "importance": 3,
        "lat": 44.3106,
        "lon": -69.7795,
        "px": 900.0,
        "py": 150.0,
        "grid_x": 112,
        "grid_y": 19,
    },
    {
        "name": "Montgomery",
        "region": "southeast",
        "importance": 3,
        "lat": 31.3792,
        "lon": -86.3077,
        "px": 663.89,
        "py": 435.56,
        "grid_x": 83,
        "grid_y": 54,
    },
    {
        "name": "Birmingham",
        "region": "southeast",
        "importance": 3,
        "lat": 33.5186,
        "lon": -86.8104,
        "px": 654.0,
        "py": 412.0,
        "grid_x": 84,
        "grid_y": 52,
    },
    {
        "name": "Charlotte",
        "region": "southeast",
        "importance": 3,
        "lat": 34.4271,
        "lon": -80.8431,
        "px": 763.2,
        "py": 363.71,
        "grid_x": 95,
        "grid_y": 45,
    },
    {
        "name": "Raleigh",
        "region": "southeast",
        "importance": 3,
        "lat": 34.9796,
        "lon": -79.6382,
        "px": 785.09,
        "py": 350.68,
        "grid_x": 98,
        "grid_y": 44,
    },
    {
        "name": "Jacksonville",
        "region": "southeast",
        "importance": 2,
        "lat": 30.3322,
        "lon": -81.6557,
        "px": 748.43,
        "py": 460.25,
        "grid_x": 94,
        "grid_y": 58,
    },
    {
        "name": "Tallahassee",
        "region": "southeast",
        "importance": 2,
        "lat": 30.4383,
        "lon": -84.2807,
        "px": 700.0,
        "py": 472.0,
        "grid_x": 88,
        "grid_y": 59,
    },
    {
        "name": "Orlando",
        "region": "southeast",
        "importance": 3,
        "lat": 28.5383,
        "lon": -81.3792,
        "px": 752.0,
        "py": 500.0,
        "grid_x": 93,
        "grid_y": 63,
    },
    {
        "name": "Tampa",
        "region": "southeast",
        "importance": 2,
        "lat": 27.9506,
        "lon": -82.4572,
        "px": 733.86,
        "py": 516.4,
        "grid_x": 92,
        "grid_y": 65,
    },
    {
        "name": "Miami",
        "region": "southeast",
        "importance": 1,
        "lat": 25.7617,
        "lon": -80.1918,
        "px": 775.03,
        "py": 568,
        "grid_x": 97,
        "grid_y": 71,
    },
    {
        "name": "Pittsburgh",
        "region": "northeast",
        "importance": 3,
        "lat": 38.7406,
        "lon": -80.3959,
        "px": 771.32,
        "py": 262.01,
        "grid_x": 96,
        "grid_y": 33,
    },
    {
        "name": "Cleveland",
        "region": "northeast",
        "importance": 3,
        "lat": 39.8993,
        "lon": -82.4944,
        "px": 733.19,
        "py": 234.7,
        "grid_x": 92,
        "grid_y": 29,
    },
    {
        "name": "Buffalo",
        "region": "northeast",
        "importance": 3,
        "lat": 41.0864,
        "lon": -80.4784,
        "px": 769.82,
        "py": 206.71,
        "grid_x": 96,
        "grid_y": 26,
    },
    {
        "name": "Albany",
        "region": "northeast",
        "importance": 3,
        "lat": 41.2526,
        "lon": -76.2562,
        "px": 846.55,
        "py": 202.79,
        "grid_x": 106,
        "grid_y": 25,
    },
    {
        "name": "New York",
        "region": "northeast",
        "importance": 1,
        "lat": 40.1128,
        "lon": -76.006,
        "px": 851.1,
        "py": 229.66,
        "grid_x": 106,
        "grid_y": 29,
    },
    {
        "name": "Philadelphia",
        "region": "northeast",
        "importance": 2,
        "lat": 39.0526,
        "lon": -76.2652,
        "px": 846.39,
        "py": 254.66,
        "grid_x": 106,
        "grid_y": 32,
    },
    {
        "name": "Baltimore",
        "region": "northeast",
        "importance": 3,
        "lat": 38.2904,
        "lon": -77.9122,
        "px": 816.46,
        "py": 272.63,
        "grid_x": 102,
        "grid_y": 34,
    },
    {
        "name": "Washington",
        "region": "northeast",
        "importance": 1,
        "lat": 37.7072,
        "lon": -78.2369,
        "px": 810.56,
        "py": 286.38,
        "grid_x": 101,
        "grid_y": 36,
    },
    {
        "name": "Boston",
        "region": "northeast",
        "importance": 2,
        "lat": 41.3601,
        "lon": -73.0589,
        "px": 904.65,
        "py": 200.26,
        "grid_x": 113,
        "grid_y": 25,
    },
    {
        "name": "Concord",
        "region": "northeast",
        "importance": 3,
        "lat": 43.2081,
        "lon": -71.5376,
        "px": 888.0,
        "py": 176.0,
        "grid_x": 111,
        "grid_y": 22,
    },
    {
        "name": "Richmond",
        "region": "northeast",
        "importance": 2,
        "lat": 37.5407,
        "lon": -77.436,
        "px": 800.0,
        "py": 320.0,
        "grid_x": 100,
        "grid_y": 40,
    },
    {
        "name": "Columbia",
        "region": "southeast",
        "importance": 2,
        "lat": 34.0007,
        "lon": -81.0348,
        "px": 755.0,
        "py": 388.0,
        "grid_x": 93,
        "grid_y": 51,
    },
]


for city in CITIES:
    population = POPULATION_MAP.get(city["name"])
    if population is None:
        raise ValueError(f"Missing population for {city['name']}")
    city["population"] = population



def register_city_seed_commands(app):
    @app.cli.command("seed-cities")
    def seed_cities():
        """Seed regions and cities for the map."""
        print("Seeding regions & cities...")

        # Regions
        region_cache = {}
        for code, name in REGIONS.items():
            region = Region.query.filter_by(code=code).first()
            if not region:
                region = Region(code=code, name=name)
                db.session.add(region)
            region_cache[code] = region

        db.session.flush()  # ať mají regiony id

        # Cities
        for data in CITIES:
            city = City.query.filter_by(name=data["name"]).first()
            if not city:
                city = City(name=data["name"])
                db.session.add(city)

            city.region = region_cache[data["region"]]
            city.importance = data["importance"]
            city.lat = data["lat"]
            city.lon = data["lon"]
            city.px = data["px"]
            city.py = data["py"]
            city.grid_x = data["grid_x"]
            city.grid_y = data["grid_y"]
            city.population = data["population"]
            state_info = STATE_MAP.get(city.name)
            if state_info:
                city.state, city.state_shortcut = state_info
            else:
                city.state = None
                city.state_shortcut = None

            # doplníme popis z mapy, pokud je k dispozici
            desc = DESCRIPTION_MAP.get(city.name)
            if desc:
                city.description = desc

        db.session.commit()
        print("✅ Seed hotový")
